### ISSUE TITLE
Regression test k3s to rancher integration

### ISSUE THREAD

**Issue by cjellick** [rancher/k3s#994] opened 2019-10-30 21:22 UTC
Want to make sure importing a k3s cluster into rancher works properly and identify any major flaws so that they can be fixed or "known issued" for this release of rancher.

**Comment by davidnuzik** [comment] 2019-11-07 17:17
Rancher v2.3.2
k3s v0.10.2

I tested by importing a couple of k3s clusters one was HA and one was not. I executed some of the basic regression tests such as from the UI regression test plan which covers:
- Apply labels to cluster and nodes (this does not work but also doesn't seem to work with rke imported cluster and a Rancher issue was created: https://github.com/rancher/rancher/issues/23840 )
- Create a workload (Deployment), Service, and Ingress and ensure my deployment is accessible
- Edit workload, service, ingress. Changes take effect.
- General UI looks good, able to see cluster details on cluster dashboard page, looks accurate, other general UI checks all high level.

Because I didn't identify any significant issues I'll go ahead and close this issue. I recommend in the future we do some more testing with Rancher.

**Closed by davidnuzik** 2019-11-07 17:17 UTC
Labels: [zube]: Next Up, kind/task
