### ISSUE TITLE
k3s in docker, metrics-server not work

### ISSUE THREAD

**Issue by huapox** [rancher/k3s#410] opened 2019-04-29 02:24 UTC
**1.before install metrics-server:**
```
kc top pod
Error from server (NotFound): the server could not find the requested resource (get services http:heapster:)
```

**2.after installation:**
```
kc top pod
Error from server (ServiceUnavailable): the server is currently unable to handle the request (get pods.metrics.k8s.io)

kc get --raw "/apis/metrics.k8s.io/v1beta1/nodes"
Error from server (ServiceUnavailable): the server is currently unable to handle the request
```

**3.the log:**
```
kc logs metrics-server-f5896c776-rnwj4 
I0429 02:21:32.068116       1 serving.go:273] Generated self-signed cert (apiserver.local.config/certificates/apiserver.crt, apiserver.local.config/certificates/apiserver.key)
W0429 02:21:33.773803       1 authentication.go:166] cluster doesn't provide client-ca-file in configmap/extension-apiserver-authentication in kube-system, so client certificate authentication to extension api-server won't work.
W0429 02:21:33.778012       1 authentication.go:210] cluster doesn't provide client-ca-file in configmap/extension-apiserver-authentication in kube-system, so client certificate authentication to extension api-server won't work.
[restful] 2019/04/29 02:21:33 log.go:33: [restful/swagger] listing is available at https://:443/swaggerapi
[restful] 2019/04/29 02:21:33 log.go:33: [restful/swagger] https://:443/swaggerui/ is mapped to folder /swagger-ui/
I0429 02:21:33.827238       1 serve.go:96] Serving securely on [::]:443
E0429 02:22:33.801216       1 manager.go:102] unable to fully collect metrics: unable to fully scrape metrics from source kubelet_summary:a4c43682c96e: unable to fetch metrics from Kubelet a4c43682c96e (2.2.0.3): Get https://2.2.0.3:10250/stats/summary/: dial tcp 2.2.0.3:10250: connect: connection refused
E0429 02:23:33.796901       1 manager.go:102] unable to fully collect metrics: unable to fully scrape metrics from source kubelet_summary:a4c43682c96e: unable to fetch metrics from Kubelet a4c43682c96e (2.2.0.3): Get https://2.2.0.3:10250/stats/summary/: dial tcp 2.2.0.3:10250: connect: connection refused
E0429 02:24:33.794865       1 manager.go:102] unable to fully collect metrics: unable to fully scrape metrics from source kubelet_summary:a4c43682c96e: unable to fetch metrics from Kubelet a4c43682c96e (2.2.0.3): Get https://2.2.0.3:10250/stats/summary/: dial tcp 2.2.0.3:10250: connect: connection refused
E0429 02:25:33.799905       1 manager.go:102] unable to fully collect metrics: unable to fully scrape metrics from source kubelet_summary:a4c43682c96e: unable to fetch metrics from Kubelet a4c43682c96e (2.2.0.3): Get https://2.2.0.3:10250/stats/summary/: dial tcp 2.2.0.3:10250: connect: connection refused
E0429 02:26:33.794800       1 manager.go:102] unable to fully collect metrics: unable to fully scrape metrics from source kubelet_summary:a4c43682c96e: unable to fetch metrics from Kubelet a4c43682c96e (2.2.0.3): Get https://2.2.0.3:10250/stats/summary/: dial tcp 2.2.0.3:10250: connect: connection refused
E0429 02:27:33.797966       1 manager.go:102] unable to fully collect metrics: unable to fully scrape metrics from source kubelet_summary:a4c43682c96e: unable to fetch metrics from Kubelet a4c43682c96e (2.2.0.3): Get https://2.2.0.3:10250/stats/summary/: dial tcp 2.2.0.3:10250: connect: connection refused
```

**Comment by huapox** [comment] 2019-04-29 03:16
**with the newest version of metrics-server:** 
- https://github.com/kubernetes-incubator/metrics-server/tree/master/deploy/1.8%2B
- image: bitnami/metrics-server:0.3.2


```
kc logs metrics-server-55d44b6849-bxtrt -f
I0429 02:47:16.239308       1 serving.go:273] Generated self-signed cert (/opt/bitnami/metrics-server/certificates/apiserver.crt, /opt/bitnami/metrics-server/certificates/apiserver.key)
W0429 02:47:16.636405       1 authentication.go:166] cluster doesn't provide client-ca-file in configmap/extension-apiserver-authentication in kube-system, so client certificate authentication to extension api-server won't work.
W0429 02:47:16.640546       1 authentication.go:210] cluster doesn't provide client-ca-file in configmap/extension-apiserver-authentication in kube-system, so client certificate authentication to extension api-server won't work.
[restful] 2019/04/29 02:47:16 log.go:33: [restful/swagger] listing is available at https://:8443/swaggerapi
[restful] 2019/04/29 02:47:16 log.go:33: [restful/swagger] https://:8443/swaggerui/ is mapped to folder /swagger-ui/
I0429 02:47:16.689678       1 serve.go:96] Serving securely on [::]:8443
E0429 02:48:16.712795       1 manager.go:111] unable to fully collect metrics: unable to fully scrape metrics from source kubelet_summary:a4c43682c96e: unable to fetch metrics from Kubelet a4c43682c96e (a4c43682c96e): Get https://a4c43682c96e:10250/stats/summary/: dial tcp: lookup a4c43682c96e on 6.7.8.10:53: no such host
E0429 02:49:16.687141       1 manager.go:111] unable to fully collect metrics: unable to fully scrape metrics from source kubelet_summary:a4c43682c96e: unable to fetch metrics from Kubelet a4c43682c96e (a4c43682c96e): Get https://a4c43682c96e:10250/stats/summary/: dial tcp: lookup a4c43682c96e on 6.7.8.10:53: no such host
E0429 02:50:16.694368       1 manager.go:111] unable to fully collect metrics: unable to fully scrape metrics from source kubelet_summary:a4c43682c96e: unable to fetch metrics from Kubelet a4c43682c96e (a4c43682c96e): Get https://a4c43682c96e:10250/stats/summary/: dial tcp: lookup a4c43682c96e on 6.7.8.10:53: no such host
```

**Comment by erikwilson** [comment] 2019-04-29 17:02
Duplicate of #386

**Closed by erikwilson** 2019-04-29 17:02 UTC
