### ISSUE TITLE
Windows Binary 

### ISSUE THREAD

**Issue by luistrigueiros** [rancher/k3s#202] opened 2019-03-09 14:13 UTC
Where can I find the windows binary it does not look to be in the released  binaries but the site  mentions support for it.

Thank you, kindly
Oscar

**Comment by jackharrhy** [comment] 2019-03-09 19:16
> Linux 3.10+

^ Mentioned in the "Minimum System Requirements" tab on https://k3s.io/, no mention of Windows support.

**Comment by bencompton** [comment] 2019-03-10 00:37
Dupe of #114?

**Comment by ibuildthecloud** [comment] 2019-03-10 02:14
We have no support for windows right now. The best bet would be to run Docker for Windows and try the `docker-compose.yml` in the root of this repo.

**Comment by deniseschannon** [comment] 2019-04-03 19:14
Closing in favor of #114

**Closed by deniseschannon** 2019-04-03 19:14 UTC
Labels: duplicate, kind/question

**Comment by coderafei** [comment] 2019-05-26 11:02
@ibuildthecloud https://github.com/rancher/k3s/blob/master/docker-compose-agent.yml can not run on windows
Failed to get system container stats for...
