### ISSUE TITLE
Do not replace link for kubectl when existing link is found

### ISSUE THREAD

**Issue by sr229** [rancher/k3s#320] opened 2019-04-10 14:04 UTC
**Is your feature request related to a problem? Please describe.**

Since I manage multiple clusters I would like to use my kubectl config instead. get.k3s.io replaces the kubectl link for some reason which is quite frustrating since I already have my own kubectl

**Describe the solution you'd like**

A much more better way is to find if `.kube/config` is found or there is data when `command -v kubectl` is used. If there is such, just append a context.

**Describe alternatives you've considered**

I redid my linking for kubectl (it overrode my kubectl snap's bindings).

**Comment by deniseschannon** [comment] 2019-04-11 18:54
This is a duplicate of https://github.com/rancher/k3s/issues/313

**Closed by deniseschannon** 2019-04-11 18:54 UTC
