### ISSUE TITLE
kubectl get cs report a wrong state

### ISSUE THREAD

**Issue by saphoooo** [rancher/k3s#124] opened 2019-03-03 15:17 UTC
running get cs returns a bad status:

```
$ kubectl get cs
NAME                 STATUS      MESSAGE                                                                                     ERROR
controller-manager   Unhealthy   Get http://127.0.0.1:10252/healthz: dial tcp 127.0.0.1:10252: connect: connection refused
scheduler            Unhealthy   Get http://127.0.0.1:10251/healthz: dial tcp 127.0.0.1:10251: connect: connection refused
```

**Comment by runningman84** [comment] 2019-03-03 17:47
Duplicate of https://github.com/rancher/k3s/issues/126

**Comment by ibuildthecloud** [comment] 2019-03-03 23:23
Closing favor of #126, thanks.

**Comment by cjellick** [comment] 2019-03-03 23:23
I'm going to go ahead an close this as a duplicate. @saphoooo you cam track #126 for updates.

**Closed** 2019-03-03 23:23 UTC
