### ISSUE TITLE
dqlite - panic: runtime error: makeslice: len out of range

### ISSUE THREAD

**Issue by alexellis** [rancher/k3s#1155] opened 2019-12-01 14:32 UTC
I'm trying to run `k3s server` with `--cluster-init` on latest Raspbian with RPi3.

Please see below for what was going wrong

Errors:

![journal](https://user-images.githubusercontent.com/6358735/69915481-49b42e00-1447-11ea-930a-e9dd7efa833b.png)
![kine-fail](https://user-images.githubusercontent.com/6358735/69915482-4a4cc480-1447-11ea-9795-d6959fbf7f7f.png)

Version:

```
pi@k5s-201:~ $ k3s --version
k3s version v1.0.0 (18bd921c)
pi@k5s-201:~ $ uname -a
Linux k5s-201 4.19.75-v7+ #1270 SMP Tue Sep 24 18:45:11 BST 2019 armv7l GNU/Linux
pi@k5s-201:~ $ cat /etc/os-release 
PRETTY_NAME="Raspbian GNU/Linux 10 (buster)"
NAME="Raspbian GNU/Linux"
VERSION_ID="10"
VERSION="10 (buster)"
VERSION_CODENAME=buster
ID=raspbian
ID_LIKE=debian
HOME_URL="http://www.raspbian.org/"
SUPPORT_URL="http://www.raspbian.org/RaspbianForums"
BUG_REPORT_URL="http://www.raspbian.org/RaspbianBugs"
pi@k5s-201:~ $ 
```

**Comment by alexellis** [comment] 2019-12-01 14:44
This is the command I was using in k3sup: `curl -sLS https://get.k3s.io | INSTALL_K3S_EXEC='server --cluster-init --tls-san 192.168.0.202 ' INSTALL_K3S_VERSION='v1.0.0' sh -`

**Comment by alexellis** [comment] 2019-12-02 19:00
cc @ibuildthecloud

**Comment by davidnuzik** [comment] 2019-12-04 16:36
Is a duplicate of https://github.com/rancher/k3s/issues/1115

**Closed by davidnuzik** 2019-12-04 16:36 UTC
