### ISSUE TITLE
Use docker mirror with container.d

### ISSUE THREAD

**Issue by simonfr** [rancher/k3s#1210] opened 2019-12-17 21:39 UTC
Hello,

I'm trying to use docker registry mirror with :

Containerd v1.16.1-k3s.1
K3S v1.16.3-k3s.2

I've modified file /var/lib/rancher/k3s/agent/etc/containerd/config.toml.tmpl on each node :
```
[plugins.opt]

  path = "/var/lib/rancher/k3s/agent/containerd"

[plugins.cri]
  stream_server_address = "127.0.0.1"
  stream_server_port = "10010"
[plugins.cri.cni]
  bin_dir = "/var/lib/rancher/k3s/data/2492a28b74abfbdbd3f943c8109a93e979669647bbbe95eadae43b60c667df69/bin"
  conf_dir = "/var/lib/rancher/k3s/agent/etc/cni/net.d"
[plugins.cri.containerd.runtimes.runc]
  runtime_type = "io.containerd.runc.v2"
[plugins.cri.registry]
  [plugins.cri.registry.mirrors]
    [plugins.cri.registry.mirrors."docker.io"]
      endpoint = ["https://mirror.gcr.io"]
```

After reboot, I check with `crictl info` all is good :
```
...
"cni": {
      "binDir": "/var/lib/rancher/k3s/data/2492a28b74abfbdbd3f943c8109a93e979669647bbbe95eadae43b60c667df69/bin",
      "confDir": "/var/lib/rancher/k3s/agent/etc/cni/net.d",
      "maxConfNum": 1,
      "confTemplate": ""
    },
    "registry": {
      "mirrors": {
        "docker.io": {
          "endpoint": [
            "https://mirror.gcr.io",
            "https://registry-1.docker.io"
          ]
        }
      },
      "configs": null,
      "auths": null
    },
    "disableTCPService": true,
    "streamServerAddress": "127.0.0.1",
    "streamServerPort": "10010",
...
```

But when I try to pull image it seems container.d always use registry-1.docker.io because when I shut down network I can see :
`pulling image failed: rpc error: code = Unknown desc = failed to pull and unpack image "docker.io/rancher/local-path-provisioner:v0.0.11": failed to resolve reference "docker.io/rancher/local-path-provisioner:v0.0.11": failed to do request: Head https://registry-1.docker.io/v2/rancher/local-path-provisioner/manifests/v0.0.11: dial tcp 3.224.11.4:443: i/o timeout`

Does anyone know why I'm having this error ?

**Comment by onedr0p** [comment] 2020-07-09 20:57
I am too trying to set up a mirror with k3s and containerd but running into simulair issues, it doesn't appear to be taking my values.

https://rancher.com/docs/k3s/latest/en/installation/private-registry/#mirrors

# /etc/rancher/k3s/registries.yaml
```
mirrors:
  docker.io:
    endpoint:
      - "http://192.168.42.120:5000"
```

However whenever I pull a new image, there's no logs in my registry. When I try it locally with Docker I see the image pulling pulled in the registry logs.

**Comment by brandond** [comment] 2020-07-09 21:14
Did you put that file on all of your nodes? What message did you get when pulling the image that indicates that it's not using the mirror?

**Comment by onedr0p** [comment] 2020-07-09 21:19
I only put it on the one node and tried pulling on that node specifically, which should yield the results I am looking for... I didn't see any errors in the `/var/lib/rancher/k3s/agent/containerd/containerd.log` logs, or anything relating.

**Comment by onedr0p** [comment] 2020-07-09 21:42
For the next person that comes to the thread looking for HTTP image mirroring, looks like it is an issue upstream and will be fixed in containerd 1.4.0

https://github.com/containerd/cri/issues/1433

**Comment by brandond** [comment] 2020-07-10 01:41
Common mistake. You have specified an endpoint for docker.io but are trying to explicitly pull from 192.168.42.120:5000. If you want to be able to pull from it explicitly, you need to configure another mirror entry for that registry.

**Comment by onedr0p** [comment] 2020-07-10 02:28
@brandond I am trying to set up a [pull-through cache](https://docs.docker.com/registry/recipes/mirror/) for my cluster using docker registry. I've spent a couple hours with different configurations, restarting agents, redeploying docker registry and nothing seems to be working. I cannot get k3s to use my cache even though it works perfectly on my macbook using docker.

**Comment by brandond** [comment] 2020-07-10 02:32
If you want to pull through for docker.io then don't put your local registry URI in the name. Leave the registry unspecified or specify docker.io.

**Comment by onedr0p** [comment] 2020-07-10 02:39
I've tried that already as I mentioned in my comment https://github.com/rancher/k3s/issues/1210#issuecomment-656347828

If I pull from docker.io using that config, the cache doesn't get populated, no errors, no logs as to why...

**Comment by brandond** [comment] 2020-07-10 22:43
The OP was on a much older release of k3s. Since you jumped on an existing issue I don't have any info on which specific version you're using, or how your environment is configured - but this has worked for me and many other people, so if you're on a recent version of k3s I suspect the issue is either your configuration, or how you're testing it.

**Comment by brandond** [comment] 2020-07-10 22:46
You could try the following, which should let you both pull directly from your registry, and have that same registry used in place of docker.io:

```yaml
mirrors:
  docker.io:
    endpoint:
      - "http://192.168.42.120:5000"
  192.168.42.120:5000:
    endpoint:
      - "http://192.168.42.120:5000"
```

**Comment by onedr0p** [comment] 2020-07-13 12:33
@bradtopol I finally got back to this. I tried what you mentioned above and I still cannot get containerd to use my docker registry as a pull thru cache. Here is more information.

```
❯ k get nodes
NAME           STATUS   ROLES    AGE   VERSION
k3s-worker-d   Ready    worker   95d   v1.18.4+k3s1
k3s-master     Ready    master   95d   v1.18.4+k3s1
k3s-worker-c   Ready    worker   95d   v1.18.4+k3s1
k3s-worker-b   Ready    worker   95d   v1.18.4+k3s1
k3s-worker-a   Ready    worker   95d   v1.18.4+k3s1
k3s-worker-e   Ready    worker   95d   v1.18.4+k3s1
```

```
sudo cat /etc/rancher/k3s/registries.yaml
mirrors:
  docker.io:
    endpoint:
      - "http://192.168.42.120:5000"
  192.168.42.120:5000:
    endpoint:
      - "http://192.168.42.120:5000"
```

```
sudo crictl info
...
    "registry": {
      "mirrors": {
        "192.168.42.120:5000": {
          "endpoint": [
            "http://192.168.42.120:5000"
          ]
        },
        "docker.io": {
          "endpoint": [
            "http://192.168.42.120:5000"
          ]
        }
      },
      "configs": null,
      "auths": null
...
```

```
sudo ctr image pull docker.io/library/traefik:latest
docker.io/library/traefik:latest:                                                 resolved       |++++++++++++++++++++++++++++++++++++++|
index-sha256:0991b33c566f8d05bffb182dcd664b9ea99e2d401ec2aa6d4cf2f08b5ec00388:    done           |++++++++++++++++++++++++++++++++++++++|
manifest-sha256:cc787df94ad97b555b43614b289cbd1d27b6941ae8ab7b491ea865d9108f5ad6: done           |++++++++++++++++++++++++++++++++++++++|
layer-sha256:ff21389d6821d06002591248b53be0d03e47ccd1d426ff04d032bd8972f80995:    done           |++++++++++++++++++++++++++++++++++++++|
layer-sha256:cbdbe7a5bc2a134ca8ec91be58565ec07d037386d1f1d8385412d224deafca08:    exists         |++++++++++++++++++++++++++++++++++++++|
config-sha256:a9dcd182440c7b69870034f0a8083c24f2d2ffa6d7919bdbff84cbe03a5d85d1:   done           |++++++++++++++++++++++++++++++++++++++|
layer-sha256:f16506d32a25436b458a7f443ec1ca0d096d99d3479523c92c247856fc6148c0:    done           |++++++++++++++++++++++++++++++++++++++|
layer-sha256:dece8d655ab616ffab2ae66dda60b30827793930bb30e38fe04fd4bce39e965f:    done           |++++++++++++++++++++++++++++++++++++++|
elapsed: 1.4 s                                                                    total:  21.3 M (15.2 MiB/s)
unpacking linux/amd64 sha256:0991b33c566f8d05bffb182dcd664b9ea99e2d401ec2aa6d4cf2f08b5ec00388...
done
```

```
k exec -it pod/registry-docker-registry-765f685446-kjtq2 -- sh
/ $ cd /var/lib/registry/
/var/lib/registry $ ls
lost+found
```

**Closed** 2020-07-14 01:32 UTC
Labels: [zube]: To Triage, kind/question
