### ISSUE TITLE
Data of Kine Increasing  Quickly Not Decrease  

### ISSUE THREAD

**Issue by liyongxian** [rancher/k3s#2004] opened 2020-07-09 07:26 UTC
**Environmental Info:**
K3s Version: 

**k3s version v1.17.2+k3s1 (cdab19b0)**
Node(s) CPU architecture, OS, and Version: 

**Linux master-1 4.4.0-176-generic #206-Ubuntu SMP Fri Feb 28 05:02:04 UTC 2020 x86_64 x86_64 x86_64 GNU/Linux**
Cluster Configuration:

2 masters, 1 workers  Backend storage is MySQL.
![k3s](https://user-images.githubusercontent.com/18571576/87008385-40b5e700-c1f6-11ea-90a1-5dd3ef2737aa.jpg)

**Describe the bug:**

K3s is running  for six days,find kine table rows is increasing quickly,but not decrease.kine rows is about 737928. 
**Statistics info:**
![statics](https://user-images.githubusercontent.com/18571576/87009650-0d745780-c1f8-11ea-8742-d147621ca80c.jpg)

**Steps To Reproduce:**

- Installed K3s: 
Offline Install
**Expected behavior:**

Table Kine rows should not be so many.
**Actual behavior:**

Kine table rows is increasing quickly,
**Additional context / logs:**

Jul  9 14:15:52 master-1 k3s[1784]: I0709 14:15:52.733454    1784 trace.go:116] Trace[333508548]: "**Update" url:/api/v1/namespaces/kube-system/endpoints/kube-scheduler,user-agent:k3s/v1.17.2+k3s1 (linux/amd64) kubernetes/cdab19b/leader-election,client:127.0.0.1 (started: 2020-07-09 14:15:52.209325242 +0800 CST m=+187778.518143779) (total time: 524.111038ms):**
Jul  9 14:15:52 master-1 k3s[1784]: Trace[333508548]: [524.064068ms] [524.007235ms] Object stored in database
Jul  9 14:16:07 master-1 k3s[1784]: I0709 14:16:07.011297    1784 controller.go:107] OpenAPI AggregationController: Processing item v1beta1.metrics.k8s.io
**Jul  9 14:16:13 master-1 k3s[1784]: time="2020-07-09T14:16:13.980050550+08:00" level=error msg="failed to record compact revision: Error 1062: Duplicate entry 'compact_rev_key-4064424' for key 'kine_name_prev_revision_uindex'"**

**Comment by liyongxian** [comment] 2020-07-09 07:32
OS Resource : 2c 4G
top info:
![top](https://user-images.githubusercontent.com/18571576/87010510-3a753a00-c1f9-11ea-9aa8-6b783bd529d2.jpg)

**Comment by liyongxian** [comment] 2020-07-09 07:49
Table Kine rows changes in 10s.
![aa](https://user-images.githubusercontent.com/18571576/87012174-7f9a6b80-c1fb-11ea-9ad8-6c995e736d8d.jpg)

**Comment by brandond** [comment] 2020-07-09 21:49
I believe this is a dupe of the issue reported in #1311

**Comment by liyongxian** [comment] 2020-07-10 01:14
@brandond  The K3s was deployed in cloud servers,but #1311 was deployed in local servers.These were different.

**Comment by brandond** [comment] 2020-07-10 01:27
The issue is caused by a HA configuration kine database log sequence getting corrupted somehow. Doesn't matter where or how it is deployed.

**Comment by liyongxian** [comment] 2020-07-10 01:52
@brandond  Gap happens in kine,it is out of order, that is no processing in code (in https://github.com/rancher/kine/blob/master/pkg/logstructured/sqllog/sql.go)

**Comment by liyongxian** [comment] 2020-07-10 01:58
Thanks @brandond  The issue is caused by the kine database log sequence getting corrupted somehow.
How Can I Resolve it? Delete the Logs??

**Comment by brandond** [comment] 2020-07-10 02:34
There's no known fix at the moment. Could probably come up with an offline fix to flatten the old revisions and reset the compact key but at the moment there's no repair short of dropping the table and rebuilding the cluster.

**Comment by liyongxian** [comment] 2020-07-10 03:27
@brandond Thanks for your timely response.Can Delete gap-xxx log In Kine? K3s Events generates too many gap-xx data.  Can Delete one row of compact_rev_key having two rows?

**Comment by brandond** [comment] 2020-07-10 06:00
It basically needs a complete resequencing. More than just deleting a few rows. I haven't had time to get into it beyond that.

**Comment by davidnuzik** [comment] 2020-10-22 01:00
Let's please track via https://github.com/rancher/k3s/issues/1311 - there is a PR there in review. This should fix the problem.

**Closed by davidnuzik** 2020-10-22 01:00 UTC
