### ISSUE TITLE
Upgrade failed from v0.9.1 to v1.0.0-rc1

### ISSUE THREAD

**Issue by runningman84** [rancher/k3s#1062] opened 2019-11-13 20:37 UTC
**Version:**
v1.0.0-rc1

**Describe the bug**
I cannot start the k3s server anymore:
```
k3s server
INFO[2019-11-13T20:33:41.973894123Z] Starting k3s v1.0.0-rc1 (670d4b41)           
INFO[2019-11-13T20:33:41.977160320Z] Kine listening on unix://kine.sock           
FATA[2019-11-13T20:33:42.003156245Z] starting kubernetes: pem does not include a valid EC private key 
```
There is also a problem reported here but it does not say what is really failing:
```
root@cubi001:~# k3s check-config

Verifying binaries in /var/lib/rancher/k3s/data/7619fab3df7062f62f50721047110e4cacfcd79fdcf31c24f63213d57ea723fa/bin:
- sha256sum: good
- links: good

System:
- iptables v1.8.3 (legacy): ok
- swap: disabled
- routes: ok

Limits:
- /proc/sys/kernel/keys/root_maxkeys: 1000000

modprobe: module configs not found in modules.dep
info: reading kernel config from /boot/config-4.15.0-69-generic ...

Generally Necessary:
- cgroup hierarchy: properly mounted [/sys/fs/cgroup]
- /sbin/apparmor_parser
apparmor: enabled and tools installed
- CONFIG_NAMESPACES: enabled
- CONFIG_NET_NS: enabled
- CONFIG_PID_NS: enabled
- CONFIG_IPC_NS: enabled
- CONFIG_UTS_NS: enabled
- CONFIG_CGROUPS: enabled
- CONFIG_CGROUP_CPUACCT: enabled
- CONFIG_CGROUP_DEVICE: enabled
- CONFIG_CGROUP_FREEZER: enabled
- CONFIG_CGROUP_SCHED: enabled
- CONFIG_CPUSETS: enabled
- CONFIG_MEMCG: enabled
- CONFIG_KEYS: enabled
- CONFIG_VETH: enabled (as module)
- CONFIG_BRIDGE: enabled (as module)
- CONFIG_BRIDGE_NETFILTER: enabled (as module)
- CONFIG_NF_NAT_IPV4: enabled (as module)
- CONFIG_IP_NF_FILTER: enabled (as module)
- CONFIG_IP_NF_TARGET_MASQUERADE: enabled (as module)
- CONFIG_NETFILTER_XT_MATCH_ADDRTYPE: enabled (as module)
- CONFIG_NETFILTER_XT_MATCH_CONNTRACK: enabled (as module)
- CONFIG_NETFILTER_XT_MATCH_IPVS: enabled (as module)
- CONFIG_IP_NF_NAT: enabled (as module)
- CONFIG_NF_NAT: enabled (as module)
- CONFIG_NF_NAT_NEEDED: enabled
- CONFIG_POSIX_MQUEUE: enabled

Optional Features:
- CONFIG_USER_NS: enabled
- CONFIG_SECCOMP: enabled
- CONFIG_CGROUP_PIDS: enabled
- CONFIG_BLK_CGROUP: enabled
- CONFIG_BLK_DEV_THROTTLING: enabled
- CONFIG_CGROUP_PERF: enabled
- CONFIG_CGROUP_HUGETLB: enabled
- CONFIG_NET_CLS_CGROUP: enabled (as module)
- CONFIG_CGROUP_NET_PRIO: enabled
- CONFIG_CFS_BANDWIDTH: enabled
- CONFIG_FAIR_GROUP_SCHED: enabled
- CONFIG_RT_GROUP_SCHED: missing
- CONFIG_IP_NF_TARGET_REDIRECT: enabled (as module)
- CONFIG_IP_VS: enabled (as module)
- CONFIG_IP_VS_NFCT: enabled
- CONFIG_IP_VS_PROTO_TCP: enabled
- CONFIG_IP_VS_PROTO_UDP: enabled
- CONFIG_IP_VS_RR: enabled (as module)
- CONFIG_EXT4_FS: enabled
- CONFIG_EXT4_FS_POSIX_ACL: enabled
- CONFIG_EXT4_FS_SECURITY: enabled
- Network Drivers:
  - "overlay":
    - CONFIG_VXLAN: enabled (as module)
      Optional (for encrypted networks):
      - CONFIG_CRYPTO: enabled
      - CONFIG_CRYPTO_AEAD: enabled
      - CONFIG_CRYPTO_GCM: enabled
      - CONFIG_CRYPTO_SEQIV: enabled
      - CONFIG_CRYPTO_GHASH: enabled
      - CONFIG_XFRM: enabled
      - CONFIG_XFRM_USER: enabled (as module)
      - CONFIG_XFRM_ALGO: enabled (as module)
      - CONFIG_INET_ESP: enabled (as module)
      - CONFIG_INET_XFRM_MODE_TRANSPORT: enabled (as module)
- Storage Drivers:
  - "overlay":
    - CONFIG_OVERLAY_FS: enabled (as module)

STATUS: fail

```

**To Reproduce**
* Install an older release
* Use it for some time
* Upgrade to latest release

**Expected behavior**
Seamless Upgrade

**Actual behavior**
Cannot start the server anymore

**Additional context**
The system is running ubuntu 18.04

**Comment by ShylajaDevadiga** [comment] 2019-11-13 23:34
@runningman84 Could you please provide the steps followed to upgrade from v0.9.1 to v1.0.0-rc1?

**Comment by runningman84** [comment] 2019-11-14 06:49
I just stopped k3s replaced the binary and started it again

**Comment by ShylajaDevadiga** [comment] 2019-11-14 22:33
Unable to reproduce the issue. Upgrades seamlessly using following set of commands. Would appreciate if you could validate these.
Start k3s server with v0.9.1 
# k3s -v 
# k3s server
Stop the server using ctrl Z
# jobs
[1]+  Stopped                 k3s server
Replace the binary to /usr/local/bin and start it either in the foreground/background
# fg %1

**Comment by erikwilson** [comment] 2019-11-14 23:31
Thanks for the info @runningman84, unfortunately I am not able to duplicated on an Ubuntu 18.04 box. Are you able to reproduce this easily on different machines, or was it a one-time issue? Was the cluster previously upgraded to v0.9.1 or was that a fresh install? Have you done anything special for the certs?

**Comment by runningman84** [comment] 2019-11-15 07:03
The cluster was originally created with version 0.1 or something like that and updated multiple times. I wasn't able to get it up and running again even with an older release. Therefore I had to delete all files and start a fresh cluster...

**Comment by cjellick** [comment] 2019-11-15 15:46
Reopening as @erikwilson identified this as being caused by us dropping support for PKCS1, which we will add back in

**Comment by cjellick** [comment] 2019-11-16 04:47
from @ibuildthecloud:

pkcs1 basically means rsa.  so you can test by installing an older version like v0.5 and then upgrade it over and over again to v1.0.0
the .key files should say RSA in them and the "EC PRIVATE KEY"

**Comment by ShylajaDevadiga** [comment] 2019-11-18 22:05
Upgrade from v0.5.0 to v1.0.0-rc6 in stages >v0.6.0->v0.7.0...>v1.0.0-rc6 is successful with the fix.
Closing issue. Please feel free to re-open if needed.

**Closed by ShylajaDevadiga** 2019-11-18 22:05 UTC
Labels: [zube]: To Test
