### ISSUE TITLE
DNS does not work with SELinux

### ISSUE THREAD

**Issue by derba** [rancher/k3s#485] opened 2019-05-17 18:53 UTC
Kube-DNS does not work for me with K3s. (I am pretty sure it works for most of you, as DNS is quite basic thing for K8s services.)
I installed K3s on 2 Fedora 30 systems with exactly the same result.

```
sudo curl -sfL https://get.k3s.io | sh -

# I am behind corporate proxy
sudo chmod 0600 /etc/systemd/system/k3s.service.env
sudo sh -c 'echo "https_proxy=http://10.1.1.1:8080/" >>/etc/systemd/system/k3s.service.env'
sudo systemctl restart k3s

rm -rf ~/.helm 2>/dev/null
sudo curl https://raw.githubusercontent.com/kubernetes/helm/master/scripts/get | sh -
kubectl -n kube-system create serviceaccount tiller
kubectl create clusterrolebinding tiller --clusterrole cluster-admin --serviceaccount=kube-system:tiller
helm init --service-account tiller

kubectl apply -f https://raw.githubusercontent.com/rancher/local-path-provisioner/master/deploy/local-path-storage.yaml
```
The trouble is that I cannot find services using DNS. E.g. this nslookup fails:
```
$ kubectl apply -f https://k8s.io/examples/admin/dns/busybox.yaml
$ kubectl wait --for=condition=Ready pod/busybox
$ kubectl exec -it busybox -- nslookup kubernetes.default
Server:    10.43.0.10
Address 1: 10.43.0.10

nslookup: can't resolve 'kubernetes.default'
```
That error message took several seconds to show up. I guess nslookup cannot connect to 10.43.0.10. It does not answer to ping.

I tried to figure out what could be wrong, but I cannot see anything wrong:
```
$ kubectl get all -n kube-system -o wide
NAME                             READY   STATUS      RESTARTS   AGE   IP          NODE                    NOMINATED NODE   READINESS GATES
pod/coredns-695688789-75xph      1/1     Running     0          31m   10.42.0.2   localhost.localdomain   <none>           <none>
pod/helm-install-traefik-gdd6b   0/1     Completed   0          31m   10.42.0.3   localhost.localdomain   <none>           <none>
pod/svclb-traefik-n7mgd          2/2     Running     0          29m   10.42.0.5   localhost.localdomain   <none>           <none>
pod/traefik-55bd9646fc-6h8jg     1/1     Running     0          29m   10.42.0.4   localhost.localdomain   <none>           <none>

NAME               TYPE           CLUSTER-IP    EXTERNAL-IP     PORT(S)                      AGE   SELECTOR
service/kube-dns   ClusterIP      10.43.0.10    <none>          53/UDP,53/TCP,9153/TCP       31m   k8s-app=kube-dns
service/traefik    LoadBalancer   10.43.29.63   10.1.1.99   80:31521/TCP,443:31833/TCP   29m   app=traefik,release=traefik

NAME                           DESIRED   CURRENT   READY   UP-TO-DATE   AVAILABLE   NODE SELECTOR   AGE   CONTAINERS               IMAGES                                                SELECTOR
daemonset.apps/svclb-traefik   1         1         1       1            1           <none>          29m   lb-port-80,lb-port-443   rancher/klipper-lb:v0.1.1,rancher/klipper-lb:v0.1.1   app=svclb-traefik

NAME                      READY   UP-TO-DATE   AVAILABLE   AGE   CONTAINERS   IMAGES                  SELECTOR
deployment.apps/coredns   1/1     1            1           31m   coredns      coredns/coredns:1.3.0   k8s-app=kube-dns
deployment.apps/traefik   1/1     1            1           29m   traefik      traefik:1.7.9           app=traefik,release=traefik

NAME                                 DESIRED   CURRENT   READY   AGE   CONTAINERS   IMAGES                  SELECTOR
replicaset.apps/coredns-695688789    1         1         1       31m   coredns      coredns/coredns:1.3.0   k8s-app=kube-dns,pod-template-hash=695688789
replicaset.apps/traefik-55bd9646fc   1         1         1       29m   traefik      traefik:1.7.9           app=traefik,pod-template-hash=55bd9646fc,release=traefik

NAME                             COMPLETIONS   DURATION   AGE   CONTAINERS   IMAGES                        SELECTOR
job.batch/helm-install-traefik   1/1           83s        31m   helm         rancher/klipper-helm:v0.1.5   controller-uid=9ab90172-78cf-11e9-b278-d0bf9c1fda20
```
I am pretty clueless. Please, help.

**Comment by eduardobcastro** [comment] 2019-05-18 23:00
This example works for me:
https://kubernetes.io/docs/tutorials/stateless-application/expose-external-ip-address/

But this doesn't and the external IP stays pending for ever:
https://kubernetes.io/docs/tutorials/stateless-application/guestbook/

**Comment by erikwilson** [comment] 2019-05-21 16:45
I think this may be an issue where we need to pass the proxy environment to all containers. We are currently doing this for helm chart manifests and adding cluster and service cidrs to `NO_PROXY`. If you add `NO_PROXY=10.43.0.0/16,10.42.0.0/16` to `/etc/systemd/system/k3s.service.env` does DNS work? If not, are you able to confirm that a firewall is not interfering and provide the output of `iptables -L`? 

Thanks!

**Comment by derba** [comment] 2019-05-22 21:20
I tried NO_PROXY, but did not help. Tried to turn VPN off, still no success.

```
Chain INPUT (policy ACCEPT)
target     prot opt source               destination         
KUBE-SERVICES  all  --  anywhere             anywhere             ctstate NEW /* kubernetes service portals */
KUBE-EXTERNAL-SERVICES  all  --  anywhere             anywhere             ctstate NEW /* kubernetes externally-visible service portals */
KUBE-FIREWALL  all  --  anywhere             anywhere            
LIBVIRT_INP  all  --  anywhere             anywhere            
ACCEPT     all  --  anywhere             anywhere             ctstate RELATED,ESTABLISHED
ACCEPT     all  --  anywhere             anywhere            
INPUT_direct  all  --  anywhere             anywhere            
INPUT_ZONES_SOURCE  all  --  anywhere             anywhere            
INPUT_ZONES  all  --  anywhere             anywhere            
DROP       all  --  anywhere             anywhere             ctstate INVALID
REJECT     all  --  anywhere             anywhere             reject-with icmp-host-prohibited

Chain FORWARD (policy DROP)
target     prot opt source               destination         
KUBE-FORWARD  all  --  anywhere             anywhere             /* kubernetes forwarding rules */
KUBE-SERVICES  all  --  anywhere             anywhere             ctstate NEW /* kubernetes service portals */
DOCKER-ISOLATION  all  --  anywhere             anywhere            
DOCKER     all  --  anywhere             anywhere            
ACCEPT     all  --  anywhere             anywhere             ctstate RELATED,ESTABLISHED
ACCEPT     all  --  anywhere             anywhere            
ACCEPT     all  --  anywhere             anywhere            
LIBVIRT_FWX  all  --  anywhere             anywhere            
LIBVIRT_FWI  all  --  anywhere             anywhere            
LIBVIRT_FWO  all  --  anywhere             anywhere            
ACCEPT     all  --  anywhere             anywhere             ctstate RELATED,ESTABLISHED
ACCEPT     all  --  anywhere             anywhere            
FORWARD_direct  all  --  anywhere             anywhere            
FORWARD_IN_ZONES_SOURCE  all  --  anywhere             anywhere            
FORWARD_IN_ZONES  all  --  anywhere             anywhere            
FORWARD_OUT_ZONES_SOURCE  all  --  anywhere             anywhere            
FORWARD_OUT_ZONES  all  --  anywhere             anywhere            
DROP       all  --  anywhere             anywhere             ctstate INVALID
REJECT     all  --  anywhere             anywhere             reject-with icmp-host-prohibited
ACCEPT     all  --  localhost.localdomain/16  anywhere            
ACCEPT     all  --  anywhere             localhost.localdomain/16 

Chain OUTPUT (policy ACCEPT)
target     prot opt source               destination         
KUBE-SERVICES  all  --  anywhere             anywhere             ctstate NEW /* kubernetes service portals */
KUBE-FIREWALL  all  --  anywhere             anywhere            
LIBVIRT_OUT  all  --  anywhere             anywhere            
OUTPUT_direct  all  --  anywhere             anywhere            

Chain DOCKER (1 references)
target     prot opt source               destination         

Chain DOCKER-ISOLATION (1 references)
target     prot opt source               destination         
RETURN     all  --  anywhere             anywhere            

Chain FORWARD_IN_ZONES (1 references)
target     prot opt source               destination         
FWDI_FedoraWorkstation  all  --  anywhere             anywhere            [goto] 
FWDI_FedoraWorkstation  all  --  anywhere             anywhere            [goto] 
FWDI_FedoraWorkstation  all  --  anywhere             anywhere            [goto] 

Chain FORWARD_IN_ZONES_SOURCE (1 references)
target     prot opt source               destination         

Chain FORWARD_OUT_ZONES (1 references)
target     prot opt source               destination         
FWDO_FedoraWorkstation  all  --  anywhere             anywhere            [goto] 
FWDO_FedoraWorkstation  all  --  anywhere             anywhere            [goto] 
FWDO_FedoraWorkstation  all  --  anywhere             anywhere            [goto] 

Chain FORWARD_OUT_ZONES_SOURCE (1 references)
target     prot opt source               destination         

Chain FORWARD_direct (1 references)
target     prot opt source               destination         

Chain FWDI_FedoraWorkstation (3 references)
target     prot opt source               destination         
FWDI_FedoraWorkstation_log  all  --  anywhere             anywhere            
FWDI_FedoraWorkstation_deny  all  --  anywhere             anywhere            
FWDI_FedoraWorkstation_allow  all  --  anywhere             anywhere            
ACCEPT     icmp --  anywhere             anywhere            

Chain FWDI_FedoraWorkstation_allow (1 references)
target     prot opt source               destination         

Chain FWDI_FedoraWorkstation_deny (1 references)
target     prot opt source               destination         

Chain FWDI_FedoraWorkstation_log (1 references)
target     prot opt source               destination         

Chain FWDO_FedoraWorkstation (3 references)
target     prot opt source               destination         
FWDO_FedoraWorkstation_log  all  --  anywhere             anywhere            
FWDO_FedoraWorkstation_deny  all  --  anywhere             anywhere            
FWDO_FedoraWorkstation_allow  all  --  anywhere             anywhere            

Chain FWDO_FedoraWorkstation_allow (1 references)
target     prot opt source               destination         

Chain FWDO_FedoraWorkstation_deny (1 references)
target     prot opt source               destination         

Chain FWDO_FedoraWorkstation_log (1 references)
target     prot opt source               destination         

Chain INPUT_ZONES (1 references)
target     prot opt source               destination         
IN_FedoraWorkstation  all  --  anywhere             anywhere            [goto] 
IN_FedoraWorkstation  all  --  anywhere             anywhere            [goto] 
IN_FedoraWorkstation  all  --  anywhere             anywhere            [goto] 

Chain INPUT_ZONES_SOURCE (1 references)
target     prot opt source               destination         

Chain INPUT_direct (1 references)
target     prot opt source               destination         

Chain IN_FedoraWorkstation (3 references)
target     prot opt source               destination         
IN_FedoraWorkstation_log  all  --  anywhere             anywhere            
IN_FedoraWorkstation_deny  all  --  anywhere             anywhere            
IN_FedoraWorkstation_allow  all  --  anywhere             anywhere            
ACCEPT     icmp --  anywhere             anywhere            

Chain IN_FedoraWorkstation_allow (1 references)
target     prot opt source               destination         
ACCEPT     tcp  --  anywhere             anywhere             tcp dpt:ssh ctstate NEW,UNTRACKED
ACCEPT     udp  --  anywhere             anywhere             udp dpt:netbios-ns ctstate NEW,UNTRACKED
ACCEPT     udp  --  anywhere             anywhere             udp dpt:netbios-dgm ctstate NEW,UNTRACKED
ACCEPT     udp  --  anywhere             224.0.0.251          udp dpt:mdns ctstate NEW,UNTRACKED
ACCEPT     udp  --  anywhere             anywhere             udp dpts:blackjack:65535 ctstate NEW,UNTRACKED
ACCEPT     tcp  --  anywhere             anywhere             tcp dpts:blackjack:65535 ctstate NEW,UNTRACKED

Chain IN_FedoraWorkstation_deny (1 references)
target     prot opt source               destination         

Chain IN_FedoraWorkstation_log (1 references)
target     prot opt source               destination         

Chain KUBE-EXTERNAL-SERVICES (1 references)
target     prot opt source               destination         

Chain KUBE-FIREWALL (2 references)
target     prot opt source               destination         
DROP       all  --  anywhere             anywhere             /* kubernetes firewall for dropping marked packets */ mark match 0x8000/0x8000

Chain KUBE-FORWARD (1 references)
target     prot opt source               destination         
ACCEPT     all  --  anywhere             anywhere             /* kubernetes forwarding rules */ mark match 0x4000/0x4000
ACCEPT     all  --  localhost.localdomain/16  anywhere             /* kubernetes forwarding conntrack pod source rule */ ctstate RELATED,ESTABLISHED
ACCEPT     all  --  anywhere             localhost.localdomain/16  /* kubernetes forwarding conntrack pod destination rule */ ctstate RELATED,ESTABLISHED

Chain KUBE-SERVICES (3 references)
target     prot opt source               destination         

Chain LIBVIRT_FWI (1 references)
target     prot opt source               destination         
ACCEPT     all  --  anywhere             192.168.122.0/24     ctstate RELATED,ESTABLISHED
REJECT     all  --  anywhere             anywhere             reject-with icmp-port-unreachable

Chain LIBVIRT_FWO (1 references)
target     prot opt source               destination         
ACCEPT     all  --  192.168.122.0/24     anywhere            
REJECT     all  --  anywhere             anywhere             reject-with icmp-port-unreachable

Chain LIBVIRT_FWX (1 references)
target     prot opt source               destination         
ACCEPT     all  --  anywhere             anywhere            

Chain LIBVIRT_INP (1 references)
target     prot opt source               destination         
ACCEPT     udp  --  anywhere             anywhere             udp dpt:domain
ACCEPT     tcp  --  anywhere             anywhere             tcp dpt:domain
ACCEPT     udp  --  anywhere             anywhere             udp dpt:bootps
ACCEPT     tcp  --  anywhere             anywhere             tcp dpt:bootps

Chain LIBVIRT_OUT (1 references)
target     prot opt source               destination         
ACCEPT     udp  --  anywhere             anywhere             udp dpt:bootpc

Chain OUTPUT_direct (1 references)
target     prot opt source               destination         
```

**Comment by erikwilson** [comment] 2019-05-22 21:22
It looks like a firewall is enabled that is dropping traffic.

**Comment by derba** [comment] 2019-05-23 12:00
Do I need to disable firewall entirely? That does not sound good.

**Comment by derba** [comment] 2019-05-23 12:25
Just for the record: I tried the Docker Compose solution mentioned in readme. I added https_proxy to environment section. On Fedora SELinux got in my way, so I disabled it by `sudo setenforce 0`. I kept the firewall in place. --> Nodes are working happily and I can do DNS lookup for the componens.

**Comment by erikwilson** [comment] 2019-05-23 14:28
I just wanted the firewall disabled temporarily to help debug the issue. 
In the same vein it may not be a great idea to completely disable SELinux.
The install script should add some SELinux permissions to the k3s executable which may help solve the issue, in case you aren't already using it. If you are using the install script then maybe you could help me track down the exact permission that SELinux is failing on for the DNS issue.

**Comment by erikwilson** [comment] 2019-05-23 14:48
Ah yah, looks like you are using the install script. If you can help find where SELinux is failing that would be appreciated, here is some info which may help do that: https://wiki.centos.org/HowTos/SELinux#head-798c98ef37cb8a00425a048152113b7a7dc14f1b

**Comment by derba** [comment] 2019-05-23 18:35
I am afraid I was not clear. The setup with the install script did not run into SELinux issues. That was the dockerized one that caused tons of SELinux issues, probably because the volume it uses.

**Comment by dgbuckley** [comment] 2019-08-03 01:50
I am also running on fedora 30 and and had no luck with DNS. I had no selinux alerts regarding k3s and `setenforce 0` did not fix the issue.  As soon as I disabled firewalld the DNS problems were gone.

I can't seem to find what is being blocked though.

**Comment by ShylajaDevadiga** [comment] 2020-08-06 05:50
@derba Could you please provide the version of k3s and command used to install k3s and If you have passed --docker flag during install. It would help reproduce the issue.
Using k3s version v1.18.6+k3s1, Fedora release 30 (Thirty), SELinux enabled DNS works as expected.
```
curl -sfL https://get.k3s.io | sh -

getenforce
Enforcing

cat /var/lib/rancher/k3s/agent/etc/containerd/config.toml  |grep selinux
  enable_selinux = true

kubectl apply -f https://k8s.io/examples/admin/dns/dnsutils.yaml
pod/dnsutils created

kubectl exec -i -t dnsutils -- nslookup kubernetes.default
Server:		10.43.0.10
Address:	10.43.0.10#53

Name:	kubernetes.default.svc.cluster.local
Address: 10.43.0.1

kubectl exec -ti dnsutils -- cat /etc/resolv.conf
search default.svc.cluster.local svc.cluster.local cluster.local us-east-2.compute.internal
nameserver 10.43.0.10
options ndots:5
```

**Comment by davidnuzik** [comment] 2020-10-06 22:28
We're working on some additional SELinux work. We'll do another pass on this later and check again. If we again cannot reproduce we plan to close the issue. Any questions/concerns - please comment.

**Comment by ShylajaDevadiga** [comment] 2020-10-14 15:54
I used the following steps to reproduce the issue. DNS is working with SELInux in Enforced mode. Please feel free to re-open the issue if problem still exists.

Node OS: Fedora 30
Environment: k3s version v1.19.2+k3s1 with docker and SELinux in Enforcing mode
```
getenforce
Enforcing

curl -sfL https://get.k3s.io | INSTALL_K3S_VERSION=v1.19.2+k3s1 INSTALL_K3S_EXEC="server" sh -s - --docker

kubectl get pods -A
NAMESPACE     NAME                                     READY   STATUS      RESTARTS   AGE
kube-system   local-path-provisioner-7ff9579c6-clw9j   1/1     Running     0          9m35s
kube-system   coredns-66c464876b-zgmjh                 1/1     Running     0          9m35s
kube-system   metrics-server-7b4f8b595-2f6kl           1/1     Running     0          9m35s
kube-system   helm-install-traefik-q7sp5               0/1     Completed   0          9m35s
kube-system   svclb-traefik-f9n67                      2/2     Running     0          9m23s
kube-system   traefik-5dd496474-sg48h                  1/1     Running     0          9m23s
default       node-hello-86df75c4d8-s64kr              1/1     Running     0          7m18s
default       dnsutils                                 1/1     Running     0          5m3s
default       busybox                                  1/1     Running     0          28s

kubectl exec -it busybox -- nslookup kubernetes.default
Server:    10.43.0.10
Address 1: 10.43.0.10 kube-dns.kube-system.svc.cluster.local

Name:      kubernetes.default
Address 1: 10.43.0.1 kubernetes.default.svc.cluster.local


ps -eZ |grep k3s
system_u:system_r:container_runtime_t:s0 18841 ? 00:01:04 k3s-server

```

**Closed by ShylajaDevadiga** 2020-10-14 15:54 UTC
Labels: [zube]: To Test
