### ISSUE TITLE
1.19.2+k3s1 embedded etcd TLS & connection refused errors after reboot

### ISSUE THREAD

**Issue by intrand** [rancher/k3s#2313] opened 2020-09-25 13:10 UTC
**Environmental Info:**
K3s Version: 
k3s version v1.19.2+k3s1 (d38505b1)

Node(s) CPU architecture, OS, and Version: 
Linux k3s0 5.4.43-1-virt #2-Alpine SMP Thu, 28 May 2020 20:13:48 UTC x86_64 Linux
Linux k3s1 5.4.43-1-virt #2-Alpine SMP Thu, 28 May 2020 20:13:48 UTC x86_64 Linux
Linux k3s2 5.4.43-1-virt #2-Alpine SMP Thu, 28 May 2020 20:13:48 UTC x86_64 Linux

Cluster Configuration:
My cluster was set up using the following commands (secrets excluded, obviously):

on `k3s0`:
```sh
INSTALL_K3S_CHANNEL=latest K3S_TOKEN=abcdefg123456 ~/k3s.sh --docker --cluster-init
```

on `k3s1` & `k3s2`:
```sh
INSTALL_K3S_CHANNEL=latest K3S_TOKEN=abcdefg123456 ~/k3s.sh --docker --server https://k3s0:6443
```

**Describe the bug:**
After a simple reboot of each node, the cluster won't come up. I see TLS and connection refused errors related to etcd in k3s.log:
```
raft2020/09/25 13:04:46 INFO: 9c939f7e77d79918 is starting a new election at term 223
raft2020/09/25 13:04:46 INFO: 9c939f7e77d79918 became candidate at term 224
raft2020/09/25 13:04:46 INFO: 9c939f7e77d79918 received MsgVoteResp from 9c939f7e77d79918 at term 224
raft2020/09/25 13:04:46 INFO: 9c939f7e77d79918 [logterm: 2, index: 12359] sent MsgVote request to 976a5417d80de829 at term 224
raft2020/09/25 13:04:46 INFO: 9c939f7e77d79918 [logterm: 2, index: 12359] sent MsgVote request to a5b03cdec1b953ba at term 224
time="2020-09-25T13:04:46.811382520Z" level=info msg="Cluster-Http-Server 2020/09/25 13:04:46 http: TLS handshake error from 172.16.30.102:59338: remote error: tls: bad certificate"
time="2020-09-25T13:04:46.813939867Z" level=info msg="Cluster-Http-Server 2020/09/25 13:04:46 http: TLS handshake error from 172.16.30.101:33834: remote error: tls: bad certificate"
2020-09-25 13:04:50.634382 W | rafthttp: health check for peer a5b03cdec1b953ba could not connect: dial tcp 172.16.30.101:2380: connect: connection refused
2020-09-25 13:04:50.634502 W | rafthttp: health check for peer 976a5417d80de829 could not connect: dial tcp 172.16.30.102:2380: connect: connection refused
2020-09-25 13:04:50.634658 W | rafthttp: health check for peer a5b03cdec1b953ba could not connect: dial tcp 172.16.30.101:2380: connect: connection refused
2020-09-25 13:04:50.634667 W | rafthttp: health check for peer 976a5417d80de829 could not connect: dial tcp 172.16.30.102:2380: connect: connection refused
```

**Steps To Reproduce:**

- Installed K3s: as above
- ssh to each node and run `reboot`
- `tail -f /var/log/k3s.log` once OSes boot up

**Expected behavior:**
etcd to start on each node, allowing the first node to serve 6443/tcp again (I realize this isn't real HA without a load balancer), then allowing the other nodes to connect to the kubernetes API and become ready.

**Actual behavior:**
```
# kubectl get nodes
Error from server (ServiceUnavailable): the server is currently unable to handle the request
```

Kubernetes API is unavailable due to unavailable database.

**Additional context / logs:**
I have tried several things to work around this issue, but regardless of what I do, (embedded) etcd refuses to come back up after (embedded) etcd quorum is lost.

**Comment by brandond** [comment] 2020-09-25 16:38
Duplicate of #2249

**Closed** 2020-09-25 16:54 UTC
