### ISSUE TITLE
Add CI pipeline to automatically build k3s-upgrade images with each release

### ISSUE THREAD

**Issue by galal-hussein** [rancher/k3s#1408] opened 2020-02-12 22:01 UTC
A new k3s-upgrade image should be created for each k3s release, this can be accomplished by github actions that listen for each release publish and trigger a dispatch event to k3s-upgrade image with the desired tag.

**Comment by davidnuzik** [comment] 2020-02-25 23:43
Since this is a task, will just close when this is complete.

**Comment by davidnuzik** [comment] 2020-03-03 20:33
As we discussed needs testing when have a build to work with.

**Comment by davidnuzik** [comment] 2020-03-25 05:37
Closing this was confirmed working

**Closed by davidnuzik** 2020-03-25 05:37 UTC
Labels: [zube]: To Test, kind/task
