### ISSUE TITLE
Issue about k3s check-config

### ISSUE THREAD

**Issue by OrwillT** [rancher/k3s#2047] opened 2020-07-22 09:57 UTC
**Environmental Info:**
K3s Version: v1.18.6+k3s1 (6f56fa1d)

Node(s) CPU architecture, OS, and Version:  Using Fedora CoreOS

`Linux stl02 5.6.19-300.fc32.x86_64 #1 SMP Wed Jun 17 16:10:48 UTC 2020 x86_64 x86_64 x86_64 GNU/Linux`

**Describe the bug:**

After a fresh install of FCOS, I tried to run `k3s check-config` and got this:

```
[core@stl02 ~]$ sudo k3s check-config /lib/modules/5.6.19-300.fc32.x86_64/config

Verifying binaries in /var/lib/rancher/k3s/data/6ab65ee0083924a980f6161177c37163fa68681b710316bb3dc59f118ff27636/bin:
- sha256sum: good
- links: good

System:
- /usr/sbin iptables v1.8.4 (legacy): ok
- swap: disabled
- routes: ok

Limits:
- /proc/sys/kernel/keys/root_maxkeys: 1000000

modprobe: module configs not found in modules.dep
info: reading kernel config from /lib/modules/5.6.19-300.fc32.x86_64/config ...

Generally Necessary:
- cgroup hierarchy: properly mounted [/sys/fs/cgroup]
- CONFIG_NAMESPACES: enabled
- CONFIG_NET_NS: enabled
- CONFIG_PID_NS: enabled
- CONFIG_IPC_NS: enabled
- CONFIG_UTS_NS: enabled
- CONFIG_CGROUPS: enabled
- CONFIG_CGROUP_CPUACCT: enabled
- CONFIG_CGROUP_DEVICE: enabled
- CONFIG_CGROUP_FREEZER: enabled
- CONFIG_CGROUP_SCHED: enabled
- CONFIG_CPUSETS: enabled
- CONFIG_MEMCG: enabled
- CONFIG_KEYS: enabled
- CONFIG_VETH: enabled (as module)
- CONFIG_BRIDGE: enabled (as module)
- CONFIG_BRIDGE_NETFILTER: enabled (as module)
- CONFIG_NF_NAT_IPV4: missing (fail)
- CONFIG_IP_NF_FILTER: enabled (as module)
- CONFIG_IP_NF_TARGET_MASQUERADE: enabled (as module)
- CONFIG_NETFILTER_XT_MATCH_ADDRTYPE: enabled (as module)
- CONFIG_NETFILTER_XT_MATCH_CONNTRACK: enabled (as module)
- CONFIG_NETFILTER_XT_MATCH_IPVS: enabled (as module)
- CONFIG_IP_NF_NAT: enabled (as module)
- CONFIG_NF_NAT: enabled (as module)
- CONFIG_NF_NAT_NEEDED: missing (fail)
- CONFIG_POSIX_MQUEUE: enabled

Optional Features:
- CONFIG_USER_NS: enabled
- CONFIG_SECCOMP: enabled
- CONFIG_CGROUP_PIDS: enabled
- CONFIG_BLK_CGROUP: enabled
- CONFIG_BLK_DEV_THROTTLING: enabled
- CONFIG_CGROUP_PERF: enabled
- CONFIG_CGROUP_HUGETLB: enabled
- CONFIG_NET_CLS_CGROUP: enabled
- CONFIG_CGROUP_NET_PRIO: enabled
- CONFIG_CFS_BANDWIDTH: enabled
- CONFIG_FAIR_GROUP_SCHED: enabled
- CONFIG_RT_GROUP_SCHED: missing
- CONFIG_IP_NF_TARGET_REDIRECT: enabled (as module)
- CONFIG_IP_SET: enabled (as module)
- CONFIG_IP_VS: enabled (as module)
- CONFIG_IP_VS_NFCT: enabled
- CONFIG_IP_VS_PROTO_TCP: enabled
- CONFIG_IP_VS_PROTO_UDP: enabled
- CONFIG_IP_VS_RR: enabled (as module)
- CONFIG_EXT4_FS: enabled
- CONFIG_EXT4_FS_POSIX_ACL: enabled
- CONFIG_EXT4_FS_SECURITY: enabled
- Network Drivers:
  - "overlay":
    - CONFIG_VXLAN: enabled (as module)
      Optional (for encrypted networks):
      - CONFIG_CRYPTO: enabled
      - CONFIG_CRYPTO_AEAD: enabled
      - CONFIG_CRYPTO_GCM: enabled
      - CONFIG_CRYPTO_SEQIV: enabled
      - CONFIG_CRYPTO_GHASH: enabled
      - CONFIG_XFRM: enabled
      - CONFIG_XFRM_USER: enabled
      - CONFIG_XFRM_ALGO: enabled
      - CONFIG_INET_ESP: enabled (as module)
      - CONFIG_INET_XFRM_MODE_TRANSPORT: missing
- Storage Drivers:
  - "overlay":
    - CONFIG_OVERLAY_FS: enabled (as module)

STATUS: 2 (fail)
```

As you can see two CONFIG failed and two missed. I asked fedora community for help and got this [answer](https://discussion.fedoraproject.org/t/how-to-add-kernel-module-to-coreos/21854/2?u=orwill):

>According to https://cateee.net/lkddb/web-lkddb/NF_NAT_NEEDED.html, https://cateee.net/lkddb/web-lkddb/NF_NAT_IPV4.html & https://cateee.net/lkddb/web-lkddb/INET_XFRM_MODE_TRANSPORT.html, those options have been removed in recent kernels (probably renamed, merged into another one or made built-in). In general, Fedora CoreOS uses the same kernel as Fedora so if it works on Fedora it should work on Fedora CoreOS.

Please check this issue and determine if you need to make changes to `k3s check-config`

**Comment by superseb** [comment] 2020-07-22 11:08
See https://github.com/rancher/k3s/issues/1291

**Comment by brandond** [comment] 2020-07-22 18:30
Yes, the modules have been renamed in newer kernels. Not many folks use check-config since it's not even mentioned in the documentation anywhere. It should probably be fixed at some point though.

**Comment by davidnuzik** [comment] 2020-08-05 15:58
https://github.com/rancher/k3s/issues/1291 I'm closing as a duplicate of this issue. Any questions please let me know. Let's track in that issue.

**Closed by davidnuzik** 2020-08-05 15:58 UTC
