### ISSUE TITLE
K3s Upgrade using System Upgrade Controller fails intermittently when run natively on a k3s cluster

### ISSUE THREAD

**Issue by ShylajaDevadiga** [rancher/k3s#1856] opened 2020-06-02 00:36 UTC
**Version:**
k3s v1.16.9 to v1.17.6
k3s v1.17.5 to v1.17.6
SUC v0.5.0

**K3s arguments:**
Default arguments

**Describe the bug**
Upgrade from the above version specified fails intermittently after plan is applied.

**To Reproduce**
1. Create a 2 node cluster, one master, one worker
2. Apply SUC v0.5.0
3. Apply the master plan
```
apiVersion: upgrade.cattle.io/v1
kind: Plan
metadata:
  name: server-plan
  namespace: system-upgrade
spec:
  concurrency: 1
  cordon: true
  nodeSelector:
    matchExpressions:
    - key: node-role.kubernetes.io/master
      operator: In
      values:
      - "true"
  serviceAccountName: system-upgrade
  upgrade:
    image: rancher/k3s-upgrade
  version: v1.17.6+k3s1
```

**Expected behavior**
Master node should be show status Ready,SchedulingDisabled.

**Actual behavior**
Unable to list nodes 
```
root@ip-172-31-30-244:~# kubectl apply -f plan.yaml 
plan.upgrade.cattle.io/server-plan created

root@ip-172-31-30-244:~# kubectl get nodes
The connection to the server 127.0.0.1:6443 was refused - did you specify the right host or port?

root@ip-172-31-30-244:~# kubectl get nodes
INFO[0000] Preparing data dir /var/lib/rancher/k3s/data/744a8a403c240a6fbd91df8ded5090391c52d7c7d12bcb1437b0a67b281d58ae 
INFO[0000] error changing modtime: chtimes /var/lib/rancher/k3s/data/744a8a403c240a6fbd91df8ded5090391c52d7c7d12bcb1437b0a67b281d58ae-tmp/bin/busybox: no such file or directory (further Chtimes errors suppressed) 
INFO[0000] error extracting tarball into /var/lib/rancher/k3s/data/744a8a403c240a6fbd91df8ded5090391c52d7c7d12bcb1437b0a67b281d58ae-tmp after 6 files, 1 dirs, 136.271475ms: symlink busybox /var/lib/rancher/k3s/data/744a8a403c240a6fbd91df8ded5090391c52d7c7d12bcb1437b0a67b281d58ae-tmp/bin/fbset: no such file or directory 
FATA[0000] extracting data: symlink busybox /var/lib/rancher/k3s/data/744a8a403c240a6fbd91df8ded5090391c52d7c7d12bcb1437b0a67b281d58ae-tmp/bin/fbset: no such file or directory 

root@ip-172-31-30-244:~# kubectl get nodes
FATA[0000] argument list too long            
```
**Additional context / logs**
```

Jun 01 23:46:40 ip-172-31-30-244 k3s[11528]: E0601 23:46:40.016613   11528 customresource_handler.go:655] error building openapi models for plans.upgrade.cattle.io: ERROR $root.definitions.io.cattle.upgrade.v1.Plan.properties.spec.properties.drain has invalid property: nullable
Jun 01 23:46:40 ip-172-31-30-244 k3s[11528]: ERROR $root.definitions.io.cattle.upgrade.v1.Plan.properties.spec.properties.drain.properties.deleteLocalData has invalid property: nullable
Jun 01 23:46:40 ip-172-31-30-244 k3s[11528]: ERROR $root.definitions.io.cattle.upgrade.v1.Plan.properties.spec.properties.drain.properties.gracePeriod has invalid property: nullable
Jun 01 23:46:40 ip-172-31-30-244 k3s[11528]: ERROR $root.definitions.io.cattle.upgrade.v1.Plan.properties.spec.properties.drain.properties.ignoreDaemonSets has invalid property: nullable
Jun 01 23:46:40 ip-172-31-30-244 k3s[11528]: ERROR $root.definitions.io.cattle.upgrade.v1.Plan.properties.spec.properties.drain.properties.timeout has invalid property: nullable
Jun 01 23:46:40 ip-172-31-30-244 k3s[11528]: ERROR $root.definitions.io.cattle.upgrade.v1.Plan.properties.spec.properties.nodeSelector has invalid property: nullable
Jun 01 23:46:40 ip-172-31-30-244 k3s[11528]: ERROR $root.definitions.io.cattle.upgrade.v1.Plan.properties.spec.properties.prepare has invalid property: nullable
Jun 01 23:46:40 ip-172-31-30-244 k3s[11528]: ERROR $root.definitions.io.cattle.upgrade.v1.Plan.properties.spec.properties.tolerations.items.<array>.properties.tolerationSeconds has invalid property: nullable
Jun 01 23:46:40 ip-172-31-30-244 k3s[11528]: ERROR $root.definitions.io.cattle.upgrade.v1.Plan.properties.spec.properties.upgrade has invalid property: nullable
Jun 01 23:47:33 ip-172-31-30-244 k3s[13937]: time="2020-06-01T23:47:33Z" level=info msg="error changing modtime: chtimes /var/lib/rancher/k3s/data/744a8a403c240a6fbd91df8ded5090391c52d7c7d12bcb1437b0a67b281d58ae-tmp/bin/containerd: no such file or directory (further Chtimes errors suppressed)"
root@ip-172-31-30-244:~# 
```

**Comment by dweomer** [comment] 2020-10-05 17:57
These log lines are screaming #1938 to me:
```
INFO[0000] error changing modtime: chtimes /var/lib/rancher/k3s/data/744a8a403c240a6fbd91df8ded5090391c52d7c7d12bcb1437b0a67b281d58ae-tmp/bin/busybox: no such file or directory (further Chtimes errors suppressed) 
INFO[0000] error extracting tarball into /var/lib/rancher/k3s/data/744a8a403c240a6fbd91df8ded5090391c52d7c7d12bcb1437b0a67b281d58ae-tmp after 6 files, 1 dirs, 136.271475ms: symlink busybox /var/lib/rancher/k3s/data/744a8a403c240a6fbd91df8ded5090391c52d7c7d12bcb1437b0a67b281d58ae-tmp/bin/fbset: no such file or directory 
FATA[0000] extracting data: symlink busybox /var/lib/rancher/k3s/data/744a8a403c240a6fbd91df8ded5090391c52d7c7d12bcb1437b0a67b281d58ae-tmp/bin/fbset: no such file or directory 
```

**Comment by davidnuzik** [comment] 2020-10-16 17:35
Should get tested now on the basis of https://github.com/rancher/k3s/issues/1938 being now fixed. These two are related. We should see if this issue remains.

**Comment by rancher-max** [comment] 2020-11-04 17:18
#### Closing this as validated. See comments.

- In our testing, we haven't been able to reproduce this after multiple attempts with different types and sizes of machines. 
- When using System Upgrade Controller v0.6.2 for the previous few k3s (and rke2) patch releases, we have not seen this issue.
- The other linked issues have been validated and closed, and this appears to have the same error so I believe is more relevant to those.
- There is the brief (approx. 3 seconds) line of: `The connection to the server 127.0.0.1:6443 was refused - did you specify the right host or port?` when running `kubectl get nodes` but this is expected to happen during an upgrade because the k3s process is being killed, so the server is down briefly. No issue with this part.

For these reasons, we feel comfortable calling this validated and closing it.

**Closed by rancher-max** 2020-11-04 17:18 UTC
Labels: [zube]: To Test, kind/bug
