### ISSUE TITLE
k3s ignore --cluster-cidr for IPv6

### ISSUE THREAD

**Issue by ultral** [rancher/k3s#918] opened 2019-10-18 14:30 UTC
`k3s version v0.10.0-rc1 (ccb1d81f)`

I'm trying to run k3s with IPv6 & it's failing because use default IPv4 instead of IPv6

```
# k3s server --docker \
  --disable-agent \
  --no-flannel \
  --no-deploy coredns \
  --no-deploy servicelb \
  --no-deploy traefik \
  --write-kubeconfig /etc/kubernetes/kubeconfig \
  --bind-address [2001:db8:3c4d:80::3] \
  --tls-san [2001:db8:3c4d:80::3] \
  --cluster-cidr "2001:db8:11::/64" \
  --service-cidr "2001:db8:12::/125" \
  --node-ip 2001:db8:3c4d:80::4 \
  --node-external-ip [2001:db8:3c4d:80::3] \
  --kube-controller-arg node-cidr-mask-size=64

INFO[2019-10-18T16:26:29.307629549+02:00] Starting k3s v0.10.0-rc1 (ccb1d81f)
INFO[2019-10-18T16:26:29.312510183+02:00] Kine listening on unix://kine.sock
INFO[2019-10-18T16:26:29.313991893+02:00] Fetching bootstrap data from etcd
INFO[2019-10-18T16:26:29.329880003+02:00] Running kube-apiserver --advertise-address=2001:db8:3c4d:80::4 --advertise-port=6443 --allow-privileged=true --anonymous-auth=false --api-audiences=unknown --authorization-mode=Node,RBAC --basic-auth-file=/var/lib/rancher/k3s/server/cred/passwd --bind-address=127.0.0.1 --cert-dir=/var/lib/rancher/k3s/server/tls/temporary-certs --client-ca-file=/var/lib/rancher/k3s/server/tls/client-ca.crt --enable-admission-plugins=NodeRestriction --etcd-servers=unix://kine.sock --insecure-port=0 --kubelet-certificate-authority=/var/lib/rancher/k3s/server/tls/server-ca.crt --kubelet-client-certificate=/var/lib/rancher/k3s/server/tls/client-kube-apiserver.crt --kubelet-client-key=/var/lib/rancher/k3s/server/tls/client-kube-apiserver.key --proxy-client-cert-file=/var/lib/rancher/k3s/server/tls/client-auth-proxy.crt --proxy-client-key-file=/var/lib/rancher/k3s/server/tls/client-auth-proxy.key --requestheader-allowed-names=system:auth-proxy --requestheader-client-ca-file=/var/lib/rancher/k3s/server/tls/request-header-ca.crt --requestheader-extra-headers-prefix=X-Remote-Extra- --requestheader-group-headers=X-Remote-Group --requestheader-username-headers=X-Remote-User --secure-port=6444 --service-account-issuer=k3s --service-account-key-file=/var/lib/rancher/k3s/server/tls/service.key --service-account-signing-key-file=/var/lib/rancher/k3s/server/tls/service.key --service-cluster-ip-range=2001:db8:12::/125 --storage-backend=etcd3 --tls-cert-file=/var/lib/rancher/k3s/server/tls/serving-kube-apiserver.crt --tls-private-key-file=/var/lib/rancher/k3s/server/tls/serving-kube-apiserver.key
Flag --basic-auth-file has been deprecated, Basic authentication mode is deprecated and will be removed in a future release. It is not recommended for production environments.
I1018 16:26:29.330119   16374 server.go:650] external host was not specified, using 2001:db8:3c4d:80::4
I1018 16:26:29.330393   16374 server.go:162] Version: v1.16.2-k3s.1
I1018 16:26:29.336625   16374 plugins.go:158] Loaded 11 mutating admission controller(s) successfully in the following order: NamespaceLifecycle,LimitRanger,ServiceAccount,NodeRestriction,TaintNodesByCondition,Priority,DefaultTolerationSeconds,DefaultStorageClass,StorageObjectInUseProtection,MutatingAdmissionWebhook,RuntimeClass.
I1018 16:26:29.336644   16374 plugins.go:161] Loaded 7 validating admission controller(s) successfully in the following order: LimitRanger,ServiceAccount,Priority,PersistentVolumeClaimResize,ValidatingAdmissionWebhook,RuntimeClass,ResourceQuota.
I1018 16:26:29.337568   16374 plugins.go:158] Loaded 11 mutating admission controller(s) successfully in the following order: NamespaceLifecycle,LimitRanger,ServiceAccount,NodeRestriction,TaintNodesByCondition,Priority,DefaultTolerationSeconds,DefaultStorageClass,StorageObjectInUseProtection,MutatingAdmissionWebhook,RuntimeClass.
I1018 16:26:29.337588   16374 plugins.go:161] Loaded 7 validating admission controller(s) successfully in the following order: LimitRanger,ServiceAccount,Priority,PersistentVolumeClaimResize,ValidatingAdmissionWebhook,RuntimeClass,ResourceQuota.
I1018 16:26:29.360853   16374 master.go:259] Using reconciler: lease
I1018 16:26:29.395536   16374 rest.go:115] the default service ipfamily for this cluster is: IPv6
W1018 16:26:29.684432   16374 genericapiserver.go:404] Skipping API batch/v2alpha1 because it has no resources.
W1018 16:26:29.718104   16374 genericapiserver.go:404] Skipping API node.k8s.io/v1alpha1 because it has no resources.
W1018 16:26:29.741340   16374 genericapiserver.go:404] Skipping API rbac.authorization.k8s.io/v1alpha1 because it has no resources.
W1018 16:26:29.745011   16374 genericapiserver.go:404] Skipping API scheduling.k8s.io/v1alpha1 because it has no resources.
W1018 16:26:29.756254   16374 genericapiserver.go:404] Skipping API storage.k8s.io/v1alpha1 because it has no resources.
W1018 16:26:29.773635   16374 genericapiserver.go:404] Skipping API apps/v1beta2 because it has no resources.
W1018 16:26:29.773655   16374 genericapiserver.go:404] Skipping API apps/v1beta1 because it has no resources.
I1018 16:26:29.782266   16374 plugins.go:158] Loaded 11 mutating admission controller(s) successfully in the following order: NamespaceLifecycle,LimitRanger,ServiceAccount,NodeRestriction,TaintNodesByCondition,Priority,DefaultTolerationSeconds,DefaultStorageClass,StorageObjectInUseProtection,MutatingAdmissionWebhook,RuntimeClass.
I1018 16:26:29.782288   16374 plugins.go:161] Loaded 7 validating admission controller(s) successfully in the following order: LimitRanger,ServiceAccount,Priority,PersistentVolumeClaimResize,ValidatingAdmissionWebhook,RuntimeClass,ResourceQuota.
INFO[2019-10-18T16:26:29.799461050+02:00] Running kube-scheduler --bind-address=127.0.0.1 --kubeconfig=/var/lib/rancher/k3s/server/cred/scheduler.kubeconfig --leader-elect=false --port=10251 --secure-port=0
I1018 16:26:29.808576   16374 server.go:143] Version: v1.16.2-k3s.1
I1018 16:26:29.808637   16374 defaults.go:91] TaintNodesByCondition is enabled, PodToleratesNodeTaints predicate is mandatory
INFO[2019-10-18T16:26:29.809226617+02:00] Running kube-controller-manager --allocate-node-cidrs=true --bind-address=127.0.0.1 --cluster-cidr=2001:db8:11::/64 --cluster-signing-cert-file=/var/lib/rancher/k3s/server/tls/server-ca.crt --cluster-signing-key-file=/var/lib/rancher/k3s/server/tls/server-ca.key --kubeconfig=/var/lib/rancher/k3s/server/cred/controller.kubeconfig --leader-elect=false --node-cidr-mask-size=64 --port=10252 --root-ca-file=/var/lib/rancher/k3s/server/tls/server-ca.crt --secure-port=0 --service-account-private-key-file=/var/lib/rancher/k3s/server/tls/service.key --use-service-account-credentials=true
I1018 16:26:29.816013   16374 controllermanager.go:161] Version: v1.16.2-k3s.1
I1018 16:26:29.816326   16374 deprecated_insecure_serving.go:53] Serving insecurely on [::]:10252
W1018 16:26:29.820112   16374 authorization.go:47] Authorization is disabled
W1018 16:26:29.820125   16374 authentication.go:79] Authentication is disabled
I1018 16:26:29.820134   16374 deprecated_insecure_serving.go:51] Serving healthz insecurely on [::]:10251
I1018 16:26:31.797847   16374 secure_serving.go:123] Serving securely on 127.0.0.1:6444
I1018 16:26:31.798714   16374 available_controller.go:383] Starting AvailableConditionController
I1018 16:26:31.798730   16374 cache.go:32] Waiting for caches to sync for AvailableConditionController controller
I1018 16:26:31.798806   16374 autoregister_controller.go:140] Starting autoregister controller
I1018 16:26:31.798818   16374 cache.go:32] Waiting for caches to sync for autoregister controller
I1018 16:26:31.799086   16374 crd_finalizer.go:274] Starting CRDFinalizer
I1018 16:26:31.799218   16374 controller.go:81] Starting OpenAPI AggregationController
I1018 16:26:31.802932   16374 crdregistration_controller.go:111] Starting crd-autoregister controller
I1018 16:26:31.802949   16374 shared_informer.go:197] Waiting for caches to sync for crd-autoregister
I1018 16:26:31.802969   16374 apiservice_controller.go:94] Starting APIServiceRegistrationController
I1018 16:26:31.802976   16374 cache.go:32] Waiting for caches to sync for APIServiceRegistrationController controller
I1018 16:26:31.803003   16374 controller.go:85] Starting OpenAPI controller
I1018 16:26:31.803024   16374 customresource_discovery_controller.go:208] Starting DiscoveryController
I1018 16:26:31.803044   16374 naming_controller.go:288] Starting NamingConditionController
I1018 16:26:31.803059   16374 establishing_controller.go:73] Starting EstablishingController
I1018 16:26:31.803078   16374 nonstructuralschema_controller.go:191] Starting NonStructuralSchemaConditionController
I1018 16:26:31.803098   16374 apiapproval_controller.go:185] Starting KubernetesAPIApprovalPolicyConformantConditionController
E1018 16:26:31.861595   16374 reflector.go:123] k8s.io/client-go@v1.16.2-k3s.1/tools/cache/reflector.go:96: Failed to list *v1.StatefulSet: statefulsets.apps is forbidden: User "system:kube-scheduler" cannot list resource "statefulsets" in API group "apps" at the cluster scope
E1018 16:26:31.862331   16374 reflector.go:123] k8s.io/client-go@v1.16.2-k3s.1/tools/cache/reflector.go:96: Failed to list *v1.Node: nodes is forbidden: User "system:kube-scheduler" cannot list resource "nodes" in API group "" at the cluster scope
E1018 16:26:31.862396   16374 reflector.go:123] k8s.io/client-go@v1.16.2-k3s.1/tools/cache/reflector.go:96: Failed to list *v1beta1.PodDisruptionBudget: poddisruptionbudgets.policy is forbidden: User "system:kube-scheduler" cannot list resource "poddisruptionbudgets" in API group "policy" at the cluster scope
E1018 16:26:31.862460   16374 reflector.go:123] k8s.io/client-go@v1.16.2-k3s.1/tools/cache/reflector.go:96: Failed to list *v1.Pod: pods is forbidden: User "system:kube-scheduler" cannot list resource "pods" in API group "" at the cluster scope
E1018 16:26:31.862516   16374 reflector.go:123] k8s.io/client-go@v1.16.2-k3s.1/tools/cache/reflector.go:96: Failed to list *v1.StorageClass: storageclasses.storage.k8s.io is forbidden: User "system:kube-scheduler" cannot list resource "storageclasses" in API group "storage.k8s.io" at the cluster scope
E1018 16:26:31.862576   16374 reflector.go:123] k8s.io/client-go@v1.16.2-k3s.1/tools/cache/reflector.go:96: Failed to list *v1.PersistentVolume: persistentvolumes is forbidden: User "system:kube-scheduler" cannot list resource "persistentvolumes" in API group "" at the cluster scope
E1018 16:26:31.862630   16374 reflector.go:123] k8s.io/client-go@v1.16.2-k3s.1/tools/cache/reflector.go:96: Failed to list *v1.PersistentVolumeClaim: persistentvolumeclaims is forbidden: User "system:kube-scheduler" cannot list resource "persistentvolumeclaims" in API group "" at the cluster scope
E1018 16:26:31.862684   16374 reflector.go:123] k8s.io/client-go@v1.16.2-k3s.1/tools/cache/reflector.go:96: Failed to list *v1.ReplicationController: replicationcontrollers is forbidden: User "system:kube-scheduler" cannot list resource "replicationcontrollers" in API group "" at the cluster scope
E1018 16:26:31.862738   16374 reflector.go:123] k8s.io/client-go@v1.16.2-k3s.1/tools/cache/reflector.go:96: Failed to list *v1.ReplicaSet: replicasets.apps is forbidden: User "system:kube-scheduler" cannot list resource "replicasets" in API group "apps" at the cluster scope
E1018 16:26:31.862880   16374 reflector.go:123] k8s.io/client-go@v1.16.2-k3s.1/tools/cache/reflector.go:96: Failed to list *v1beta1.CSINode: csinodes.storage.k8s.io is forbidden: User "system:kube-scheduler" cannot list resource "csinodes" in API group "storage.k8s.io" at the cluster scope
E1018 16:26:31.862942   16374 reflector.go:123] k8s.io/client-go@v1.16.2-k3s.1/tools/cache/reflector.go:96: Failed to list *v1.Service: services is forbidden: User "system:kube-scheduler" cannot list resource "services" in API group "" at the cluster scope
INFO[2019-10-18T16:26:31.870258866+02:00] Running cloud-controller-manager --allocate-node-cidrs=true --allow-untagged-cloud=true --bind-address=127.0.0.1 --cloud-provider=k3s --cluster-cidr=2001:db8:11::/64 --kubeconfig=/var/lib/rancher/k3s/server/cred/cloud-controller.kubeconfig --leader-elect=false --node-status-update-frequency=1m --secure-port=0
Flag --allow-untagged-cloud has been deprecated, This flag is deprecated and will be removed in a future release. A cluster-id will be required on cloud instances.
I1018 16:26:31.877974   16374 controllermanager.go:117] Version: v1.16.2-k3s.1
W1018 16:26:31.877996   16374 controllermanager.go:129] detected a cluster without a ClusterID.  A ClusterID will be required in the future.  Please tag your cluster to avoid any future issues
I1018 16:26:31.882552   16374 node_controller.go:71] Sending events to api server.
I1018 16:26:31.882602   16374 controllermanager.go:244] Started "cloud-node"
I1018 16:26:31.885086   16374 node_lifecycle_controller.go:77] Sending events to api server
I1018 16:26:31.885122   16374 controllermanager.go:244] Started "cloud-node-lifecycle"
E1018 16:26:31.887478   16374 core.go:85] Failed to start service controller: the cloud provider does not support external load balancers
W1018 16:26:31.887494   16374 controllermanager.go:241] Skipping "service"
W1018 16:26:31.887503   16374 core.go:103] configure-cloud-routes is set, but cloud provider does not support routes. Will not configure cloud provider routes.
W1018 16:26:31.887510   16374 controllermanager.go:241] Skipping "route"
INFO[2019-10-18T16:26:31.901709683+02:00] Writing static file: /var/lib/rancher/k3s/server/static/charts/traefik-1.77.1.tgz
INFO[2019-10-18T16:26:31.901982285+02:00] Writing manifest: /var/lib/rancher/k3s/server/manifests/ccm.yaml
INFO[2019-10-18T16:26:31.902110786+02:00] Writing manifest: /var/lib/rancher/k3s/server/manifests/local-storage.yaml
INFO[2019-10-18T16:26:31.902208487+02:00] Writing manifest: /var/lib/rancher/k3s/server/manifests/rolebindings.yaml
E1018 16:26:31.902244   16374 node_controller.go:148] NodeAddress: Error fetching by providerID: unimplemented Error fetching by NodeName: Failed to find node lindev-lgonchar: node "lindev-lgonchar" not found
I1018 16:26:31.908434   16374 cache.go:39] Caches are synced for AvailableConditionController controller
I1018 16:26:31.908694   16374 cache.go:39] Caches are synced for autoregister controller
I1018 16:26:31.909117   16374 shared_informer.go:204] Caches are synced for crd-autoregister
I1018 16:26:31.909177   16374 cache.go:39] Caches are synced for APIServiceRegistrationController controller
W1018 16:26:31.920015   16374 lease.go:222] Resetting endpoints for master service "kubernetes" to [2001:db8:3c4d:80::4]
I1018 16:26:31.921246   16374 controller.go:606] quota admission added evaluator for: endpoints
INFO[2019-10-18T16:26:31.933704805+02:00] Listening on [2001:db8:3c4d:80::3]:6443
E1018 16:26:31.976293   16374 controller.go:158] Unable to remove old endpoints from kubernetes service: no master IPs were listed in storage, refusing to erase all endpoints for the kubernetes service
E1018 16:26:31.978725   16374 repair.go:247] the cluster IP 10.43.0.1 for service kubernetes/default is not within the service CIDR 2001:db8:12::/125; please recreate
E1018 16:26:31.978819   16374 repair.go:247] the cluster IP 10.43.0.10 for service kube-dns/kube-system is not within the service CIDR 2001:db8:12::/125; please recreate
E1018 16:26:31.989133   16374 repair.go:247] the cluster IP 10.43.0.1 for service kubernetes/default is not within the service CIDR 2001:db8:12::/125; please recreate
E1018 16:26:31.989160   16374 repair.go:247] the cluster IP 10.43.0.10 for service kube-dns/kube-system is not within the service CIDR 2001:db8:12::/125; please recreate
INFO[2019-10-18T16:26:32.034054598+02:00] Starting k3s.cattle.io/v1, Kind=Addon controller
INFO[2019-10-18T16:26:32.034913504+02:00] Node token is available at /var/lib/rancher/k3s/server/node-token
INFO[2019-10-18T16:26:32.034936004+02:00] To join node to cluster: k3s agent -s https://192.168.128.147:6443 -t ${NODE_TOKEN}
INFO[2019-10-18T16:26:32.035219906+02:00] Starting k3s.cattle.io/v1, Kind=ListenerConfig controller
INFO[2019-10-18T16:26:32.035546209+02:00] Waiting for master node  startup: node "" not found
INFO[2019-10-18T16:26:32.137551814+02:00] Starting /v1, Kind=Service controller
INFO[2019-10-18T16:26:32.137708815+02:00] Starting helm.cattle.io/v1, Kind=HelmChart controller
INFO[2019-10-18T16:26:32.137880516+02:00] Starting batch/v1, Kind=Job controller
INFO[2019-10-18T16:26:32.138009317+02:00] Starting /v1, Kind=Pod controller
INFO[2019-10-18T16:26:32.138148318+02:00] Starting /v1, Kind=Endpoints controller
INFO[2019-10-18T16:26:32.138290619+02:00] Starting /v1, Kind=Node controller
INFO[2019-10-18T16:26:32.143921558+02:00] Wrote kubeconfig /etc/kubernetes/kubeconfig
INFO[2019-10-18T16:26:32.143948858+02:00] Run: k3s kubectl
INFO[2019-10-18T16:26:32.143958858+02:00] k3s is up and running
E1018 16:26:32.162248   16374 controller.go:117] error syncing 'kube-system/traefik': handler helm-controller: failed to update kube-system/helm-install-traefik batch/v1, Kind=Job for helm-controller kube-system/traefik: replace job, requeuing
E1018 16:26:32.176816   16374 controller.go:117] error syncing 'kube-system/traefik': handler helm-controller: failed to update kube-system/helm-install-traefik batch/v1, Kind=Job for helm-controller kube-system/traefik: replace job, requeuing
I1018 16:26:32.179530   16374 controller.go:606] quota admission added evaluator for: addons.k3s.cattle.io
E1018 16:26:32.190109   16374 controller.go:117] error syncing 'kube-system/traefik': handler helm-controller: failed to update kube-system/helm-install-traefik batch/v1, Kind=Job for helm-controller kube-system/traefik: replace job, requeuing
E1018 16:26:32.275212   16374 controller.go:117] error syncing 'kube-system/traefik': handler helm-controller: failed to update kube-system/helm-install-traefik batch/v1, Kind=Job for helm-controller kube-system/traefik: replace job, requeuing
E1018 16:26:32.440321   16374 controller.go:117] error syncing 'kube-system/traefik': handler helm-controller: failed to update kube-system/helm-install-traefik batch/v1, Kind=Job for helm-controller kube-system/traefik: replace job, requeuing
E1018 16:26:32.765915   16374 controller.go:117] error syncing 'kube-system/traefik': handler helm-controller: failed to update kube-system/helm-install-traefik batch/v1, Kind=Job for helm-controller kube-system/traefik: replace job, requeuing
I1018 16:26:32.797932   16374 controller.go:107] OpenAPI AggregationController: Processing item
I1018 16:26:32.797951   16374 controller.go:130] OpenAPI AggregationController: action for item : Nothing (removed from the queue).
I1018 16:26:32.797962   16374 controller.go:130] OpenAPI AggregationController: action for item k8s_internal_local_delegation_chain_0000000000: Nothing (removed from the queue).
I1018 16:26:32.800564   16374 storage_scheduling.go:148] all system priority classes are created successfully or already exist.
INFO[2019-10-18T16:26:33.035670923+02:00] Waiting for master node  startup: node "" not found
E1018 16:26:33.410851   16374 controller.go:117] error syncing 'kube-system/traefik': handler helm-controller: failed to update kube-system/helm-install-traefik batch/v1, Kind=Job for helm-controller kube-system/traefik: replace job, requeuing
INFO[2019-10-18T16:26:34.035842538+02:00] Waiting for master node  startup: node "" not found
I1018 16:26:34.176601   16374 plugins.go:100] No cloud provider specified.
I1018 16:26:34.179501   16374 shared_informer.go:197] Waiting for caches to sync for tokens
I1018 16:26:34.189643   16374 node_lifecycle_controller.go:77] Sending events to api server
E1018 16:26:34.189680   16374 core.go:201] failed to start cloud node lifecycle controller: no cloud provider provided
W1018 16:26:34.189693   16374 controllermanager.go:526] Skipping "cloud-node-lifecycle"
I1018 16:26:34.279646   16374 shared_informer.go:204] Caches are synced for tokens
E1018 16:26:34.696722   16374 controller.go:117] error syncing 'kube-system/traefik': handler helm-controller: failed to update kube-system/helm-install-traefik batch/v1, Kind=Job for helm-controller kube-system/traefik: replace job, requeuing
I1018 16:26:34.806929   16374 controllermanager.go:534] Started "garbagecollector"
I1018 16:26:34.807314   16374 garbagecollector.go:130] Starting garbage collector controller
I1018 16:26:34.807325   16374 shared_informer.go:197] Waiting for caches to sync for garbage collector
I1018 16:26:34.807349   16374 graph_builder.go:282] GraphBuilder running
I1018 16:26:34.816436   16374 controllermanager.go:534] Started "csrsigning"
I1018 16:26:34.816548   16374 certificate_controller.go:113] Starting certificate controller
I1018 16:26:34.816559   16374 shared_informer.go:197] Waiting for caches to sync for certificate
E1018 16:26:34.823743   16374 core.go:78] Failed to start service controller: WARNING: no cloud provider provided, services of type LoadBalancer will fail
W1018 16:26:34.823803   16374 controllermanager.go:526] Skipping "service"
I1018 16:26:34.831110   16374 controllermanager.go:534] Started "pvc-protection"
I1018 16:26:34.831137   16374 pvc_protection_controller.go:100] Starting PVC protection controller
I1018 16:26:34.831153   16374 shared_informer.go:197] Waiting for caches to sync for PVC protection
I1018 16:26:34.838377   16374 controllermanager.go:534] Started "podgc"
I1018 16:26:34.838463   16374 gc_controller.go:75] Starting GC controller
I1018 16:26:34.838484   16374 shared_informer.go:197] Waiting for caches to sync for GC
I1018 16:26:34.864049   16374 controllermanager.go:534] Started "horizontalpodautoscaling"
I1018 16:26:34.864145   16374 horizontal.go:156] Starting HPA controller
I1018 16:26:34.864155   16374 shared_informer.go:197] Waiting for caches to sync for HPA
I1018 16:26:34.871199   16374 controllermanager.go:534] Started "ttl"
I1018 16:26:34.871299   16374 ttl_controller.go:116] Starting TTL controller
I1018 16:26:34.871313   16374 shared_informer.go:197] Waiting for caches to sync for TTL
I1018 16:26:34.877941   16374 controllermanager.go:534] Started "attachdetach"
I1018 16:26:34.878058   16374 attach_detach_controller.go:334] Starting attach detach controller
I1018 16:26:34.878069   16374 shared_informer.go:197] Waiting for caches to sync for attach detach
I1018 16:26:34.959616   16374 controllermanager.go:534] Started "endpoint"
W1018 16:26:34.959633   16374 controllermanager.go:513] "endpointslice" is disabled
I1018 16:26:34.959675   16374 endpoints_controller.go:176] Starting endpoint controller
I1018 16:26:34.959684   16374 shared_informer.go:197] Waiting for caches to sync for endpoint
INFO[2019-10-18T16:26:35.036005252+02:00] Waiting for master node  startup: node "" not found
I1018 16:26:35.109898   16374 controllermanager.go:534] Started "replicaset"
I1018 16:26:35.109947   16374 replica_set.go:182] Starting replicaset controller
I1018 16:26:35.109957   16374 shared_informer.go:197] Waiting for caches to sync for ReplicaSet
I1018 16:26:35.260300   16374 controllermanager.go:534] Started "persistentvolume-expander"
I1018 16:26:35.260353   16374 expand_controller.go:300] Starting expand controller
I1018 16:26:35.260363   16374 shared_informer.go:197] Waiting for caches to sync for expand
I1018 16:26:35.409663   16374 controllermanager.go:534] Started "clusterrole-aggregation"
W1018 16:26:35.409687   16374 controllermanager.go:526] Skipping "ttl-after-finished"
W1018 16:26:35.409695   16374 controllermanager.go:513] "bootstrapsigner" is disabled
W1018 16:26:35.409708   16374 core.go:215] configure-cloud-routes is set, but no cloud provider specified. Will not configure cloud provider routes.
W1018 16:26:35.409717   16374 controllermanager.go:526] Skipping "route"
I1018 16:26:35.409754   16374 clusterroleaggregation_controller.go:148] Starting ClusterRoleAggregator
I1018 16:26:35.409789   16374 shared_informer.go:197] Waiting for caches to sync for ClusterRoleAggregator
I1018 16:26:35.559725   16374 controllermanager.go:534] Started "persistentvolume-binder"
I1018 16:26:35.559865   16374 pv_controller_base.go:282] Starting persistent volume controller
I1018 16:26:35.559876   16374 shared_informer.go:197] Waiting for caches to sync for persistent volume
I1018 16:26:35.709473   16374 node_ipam_controller.go:94] Sending events to api server.
INFO[2019-10-18T16:26:36.036140667+02:00] Waiting for master node  startup: node "" not found
INFO[2019-10-18T16:26:37.036253681+02:00] Waiting for master node  startup: node "" not found
E1018 16:26:37.262190   16374 controller.go:117] error syncing 'kube-system/traefik': handler helm-controller: failed to update kube-system/helm-install-traefik batch/v1, Kind=Job for helm-controller kube-system/traefik: replace job, requeuing
INFO[2019-10-18T16:26:38.036429096+02:00] Waiting for master node  startup: node "" not found
INFO[2019-10-18T16:26:39.036590810+02:00] Waiting for master node  startup: node "" not found
INFO[2019-10-18T16:26:40.036729625+02:00] Waiting for master node  startup: node "" not found
INFO[2019-10-18T16:26:41.036920240+02:00] Waiting for master node  startup: node "" not found
INFO[2019-10-18T16:26:42.037081254+02:00] Waiting for master node  startup: node "" not found
E1018 16:26:42.388555   16374 controller.go:117] error syncing 'kube-system/traefik': handler helm-controller: failed to update kube-system/helm-install-traefik batch/v1, Kind=Job for helm-controller kube-system/traefik: replace job, requeuing
INFO[2019-10-18T16:26:43.037222269+02:00] Waiting for master node  startup: node "" not found
INFO[2019-10-18T16:26:44.037386283+02:00] Waiting for master node  startup: node "" not found
INFO[2019-10-18T16:26:45.037556398+02:00] Waiting for master node  startup: node "" not found
I1018 16:26:45.712124   16374 range_allocator.go:82] Sending events to api server.
I1018 16:26:45.712217   16374 range_allocator.go:110] No Service CIDR provided. Skipping filtering out service addresses.
I1018 16:26:45.712230   16374 range_allocator.go:116] No Secondary Service CIDR provided. Skipping filtering out secondary service addresses.
E1018 16:26:45.712257   16374 controllermanager.go:522] Error starting "nodeipam"
F1018 16:26:45.712268   16374 controllermanager.go:235] error starting controllers: failed to mark cidr[10.42.0.0/24] at idx [0] as occupied for node: lindev-lgonchar: cidr 10.42.0.0/24 is out the range of cluster cidr 2001:db8:11::/64

```

**Expected behavior**
cluster cidr is "2001:db8:11::/64"

**Actual behavior**
cluster cidr is default "10.42.0.0/24"

**Comment by unixfox** [comment] 2019-10-18 19:20
Probably related to https://github.com/rancher/k3s/issues/284

**Comment by davidnuzik** [comment] 2019-11-05 16:19
Essentially a duplicate of https://github.com/rancher/k3s/issues/284
If you disagree let us know.

**Closed** 2019-11-05 16:19 UTC
Labels: [zube]: Done
