### ISSUE TITLE
k3s crictl --help shows unknown version

### ISSUE THREAD

**Issue by dnoland1** [rancher/k3s#334] opened 2019-04-11 19:47 UTC
**Describe the bug**
`k3s crictl --help` shows unknown version. Note, `k3s crictl version` works fine.

**To Reproduce**
```
$ k3s crictl -h
NAME:
   crictl - client for CRI

USAGE:
   crictl [global options] command [command options] [arguments...]

VERSION:
   unknown

COMMANDS:
...
```

**Expected behavior**
Should show the version instead of `unknown`

**Additional context**
```
$ k3s -v
k3s version v0.3.0 (9a1a1ec)
$ k3s crictl version
Version:  0.1.0
RuntimeName:  containerd
RuntimeVersion:  1.2.4+unknown
RuntimeApiVersion:  v1alpha2
```
This issue could be the same or related to https://github.com/rancher/k3s/issues/236

**Comment by erikwilson** [comment] 2019-04-17 15:36
I think this is a duplicate of #236, so closing, thanks for reporting tho @dnoland1. Looks like we will need to update some packages that are currently forked and being maintained by @ibuildthecloud.

**Closed by erikwilson** 2019-04-17 15:36 UTC
