### ISSUE TITLE
Add --docker flag to k3s server

### ISSUE THREAD

**Issue by dmarkey** [rancher/k3s#125] opened 2019-03-03 15:23 UTC
**Is your feature request related to a problem? Please describe.**
No.

**Describe the solution you'd like**
I'd like the --docker flag to be added to k3s server so it can be passed to the agent (saves having to start the agent separately)

**Describe alternatives you've considered**
Creating the agent separately but it's inconvenient.

**Comment by ibuildthecloud** [comment] 2019-03-03 23:26
Duplicate of https://github.com/rancher/k3s/issues/73, This should be fixed in the next RC, there's a PR in already https://github.com/rancher/k3s/pull/111

**Closed by ibuildthecloud** 2019-03-03 23:26 UTC
