### ISSUE TITLE
[Documentation] A "pre-requisites" section / a list of recommended distros

### ISSUE THREAD

**Issue by lukapeschke** [rancher/k3s#982] opened 2019-10-29 10:50 UTC
**Is your feature request related to a problem? Please describe.**

First of all, thanks for your work on k3s, I really like it!

I've been deploying k3s on debian Buster and everything seemed to be working fine, until I noticed that my containers were unable to reach the internet. Being a network noob, I spent several days troubleshooting and not understanding what was happening (seemed like a DNS issue at first), and re-deploying from scratch several times on different environments (VM and Baremetal). From what I could see in other issues and tweets, it seems that my issue was caused by `iptables` running in `nftables` mode instead of legacy. I had no issues at all when re-deploying the exact same way on ubuntu 18.04 (iptables 1.6.1)

**Describe the solution you'd like**

A small pre-requisites section detailing the pre-installation requirements such as legacy iptables, and maybe a list of recommended distros for testing (ex: debian<10 or centos<8, ubuntu==18.04). Also, a few commands or some links to external documentation explaining how to match the requirements would be great (for example the debian docs on iptables have been really helpful for me https://wiki.debian.org/iptables)

I'd be glad to help on this if you think it'd be useful.

**Describe alternatives you've considered**

https://github.com/rancher/k3s/pull/914 is really great, but having the checks it makes in the documentation would be a big plus IMO.

**Additional context**

**Comment by davidnuzik** [comment] 2019-10-29 15:53
It looks like this is a duplicate of https://github.com/rancher/k3s/issues/857 although there is some additional input that I think is a good call such as any requirements for iptables, etc. I will make note of this.

**Closed by davidnuzik** 2019-10-29 15:53 UTC

**Comment by lukapeschke** [comment] 2019-10-29 15:56
Indeed, I missed that issue, sorry

**Comment by davidnuzik** [comment] 2019-10-29 15:57
No worries thank you for your recommendations
