### ISSUE TITLE
HelmChart `spec.set` doesn't support boolean values

### ISSUE THREAD

**Issue by pmahoney** [rancher/k3s#748] opened 2019-08-21 18:03 UTC
**Describe the bug**

HelmChart resource does not correctly pass boolean values with `set.spec`.

**To Reproduce**

(running k3s 0.8.0)

with HelmChart
```
spec:
  set:
    something.enabled: false
```
I see the following in k3s server logs:
```
E0821 17:40:52.102494       1 reflector.go:126] github.com/rancher/helm-controller/pkg/generated/informers/externalversions/factory.go:117: Failed to list *v1.HelmChart: v1.HelmChartList.Items: []v1.HelmChart: v1.HelmChart.Spec: v1.HelmChartSpec.Set: unmarshalerDecoder: json: cannot unmarshal bool into Go value of type int32, error found in #10 byte of ...|led":false,"somethin|..., bigger context ...|33664d7589.tgz","set":{"something.enabled":false,|...
```
and no `helm-install-$name` job is ever created.

with HelmChart
```
spec:
  set:
    something.enabled: "false"
```
I see the following in `helm-install-$name` job pod's logs:
```
+ helm install --name $name http://$url.tgz --namespace default --set-string something.enabled=false
```

And "something" feature is actually **enabled** because a string "false" is truthy.

**Expected behavior**

I expect some way to pass a boolean via `spec.set` to a helm commandline.

**Additional context**
It appears [helm-controller](https://github.com/rancher/helm-controller/blob/4b4c89575c6598b8e0bcd9e1ad3014469ed4f001/pkg/helm/controller.go#L321-L327) supports only string or int values.

**Comment by erikwilson** [comment] 2019-08-21 18:30
Duplicate of #276

**Closed** 2020-01-21 18:39 UTC
Labels: duplicate
