### ISSUE TITLE
Raspberry Pi 3 B fails after k3s v0.9.1

### ISSUE THREAD

**Issue by Rambou** [rancher/k3s#1004] opened 2019-11-02 19:56 UTC
**Version:**
I've tried all the version above v0.4.0 and all of them fail (except 0.9.1 - latest known version to work). The latest version 0.10.0 fails with an error below.
```
-- Unit k3s.service has begun starting up.
Nov 02 19:39:52 k3s-master k3s[4208]: time="2019-11-02T19:39:52.136821256Z" level=info msg="Starting k3s v0.10.2 (8833bfd9)"
Nov 02 19:39:52 k3s-master k3s[4208]: time="2019-11-02T19:39:52.148794012Z" level=info msg="Kine listening on unix://kine.sock"
Nov 02 19:39:52 k3s-master k3s[4208]: time="2019-11-02T19:39:52.151929011Z" level=info msg="Fetching bootstrap data from etcd"
Nov 02 19:39:52 k3s-master k3s[4208]: time="2019-11-02T19:39:52.176148273Z" level=info msg="Running kube-apiserver --advertise-port=6443 --allow-privileged=true --anonymous-auth=false --api-audiences=unknown --authorization-mode=Node,RBAC --basic-auth-file=/var/lib/rancher/k3s/server/cred/passwd --bind-address=127.0.0.1 --cert-dir=/var/lib/rancher/k3s/server/tls/temporary-certs --client-ca-file=/var/lib/rancher/k3s/server/tls/client-ca.crt --enable-admission-plugins=NodeRestriction --etcd-servers=unix://kine.sock --insecure-port=0 --kubelet-certificate-authority=/var/lib/rancher/k3s/server/tls/server-ca.crt --kubelet-client-certificate=/var/lib/rancher/k3s/server/tls/client-kube-apiserver.crt --kubelet-client-key=/var/lib/rancher/k3s/server/tls/client-kube-apiserver.key --proxy-client-cert-file=/var/lib/rancher/k3s/server/tls/client-auth-proxy.crt --proxy-client-key-file=/var/lib/rancher/k3s/server/tls/client-auth-proxy.key --requestheader-allowed-names=system:auth-proxy --requestheader-client-ca-file=/var/lib/rancher/k3s/server/tls/request-header-ca.crt --requestheader-extra-headers-prefix=X-Remote-Extra- --requestheader-group-headers=X-Remote-Group --requestheader-username-headers=X-Remote-User --secure-port=6444 --service-account-issuer=k3s --service-account-key-file=/var/lib/rancher/k3s/server/tls/service.key --service-account-signing-key-file=/var/lib/rancher/k3s/server/tls/service.key --service-cluster-ip-range=10.43.0.0/16 --storage-backend=etcd3 --tls-cert-file=/var/lib/rancher/k3s/server/tls/serving-kube-apiserver.crt --tls-private-key-file=/var/lib/rancher/k3s/server/tls/serving-kube-apiserver.key"
Nov 02 19:39:52 k3s-master k3s[4208]: Flag --basic-auth-file has been deprecated, Basic authentication mode is deprecated and will be removed in a future release. It is not recommended for production environments.
Nov 02 19:39:52 k3s-master k3s[4208]: I1102 19:39:52.181521    4208 server.go:650] external host was not specified, using 192.168.1.102
Nov 02 19:39:52 k3s-master k3s[4208]: I1102 19:39:52.183475    4208 server.go:162] Version: v1.16.2-k3s.1
Nov 02 19:39:52 k3s-master k3s[4208]: I1102 19:39:52.219518    4208 plugins.go:158] Loaded 11 mutating admission controller(s) successfully in the following order: NamespaceLifecycle,LimitRanger,ServiceAccount,NodeRestriction,TaintNodesByCondition,Priority,DefaultTolerationSeconds,DefaultStorageClass,StorageObjectInUseProtection,MutatingAdmissionWebhook,RuntimeClass.
Nov 02 19:39:52 k3s-master k3s[4208]: I1102 19:39:52.219865    4208 plugins.go:161] Loaded 7 validating admission controller(s) successfully in the following order: LimitRanger,ServiceAccount,Priority,PersistentVolumeClaimResize,ValidatingAdmissionWebhook,RuntimeClass,ResourceQuota.
Nov 02 19:39:52 k3s-master k3s[4208]: I1102 19:39:52.226290    4208 plugins.go:158] Loaded 11 mutating admission controller(s) successfully in the following order: NamespaceLifecycle,LimitRanger,ServiceAccount,NodeRestriction,TaintNodesByCondition,Priority,DefaultTolerationSeconds,DefaultStorageClass,StorageObjectInUseProtection,MutatingAdmissionWebhook,RuntimeClass.
Nov 02 19:39:52 k3s-master k3s[4208]: I1102 19:39:52.226432    4208 plugins.go:161] Loaded 7 validating admission controller(s) successfully in the following order: LimitRanger,ServiceAccount,Priority,PersistentVolumeClaimResize,ValidatingAdmissionWebhook,RuntimeClass,ResourceQuota.
Nov 02 19:39:52 k3s-master k3s[4208]: I1102 19:39:52.359585    4208 master.go:259] Using reconciler: lease
Nov 02 19:39:52 k3s-master k3s[4208]: I1102 19:39:52.508013    4208 rest.go:115] the default service ipfamily for this cluster is: IPv4
Nov 02 19:39:54 k3s-master k3s[4208]: W1102 19:39:54.120244    4208 genericapiserver.go:404] Skipping API batch/v2alpha1 because it has no resources.
Nov 02 19:39:54 k3s-master k3s[4208]: W1102 19:39:54.255577    4208 genericapiserver.go:404] Skipping API node.k8s.io/v1alpha1 because it has no resources.
Nov 02 19:39:54 k3s-master k3s[4208]: W1102 19:39:54.376391    4208 genericapiserver.go:404] Skipping API rbac.authorization.k8s.io/v1alpha1 because it has no resources.
Nov 02 19:39:54 k3s-master k3s[4208]: W1102 19:39:54.398931    4208 genericapiserver.go:404] Skipping API scheduling.k8s.io/v1alpha1 because it has no resources.
Nov 02 19:39:54 k3s-master k3s[4208]: W1102 19:39:54.474425    4208 genericapiserver.go:404] Skipping API storage.k8s.io/v1alpha1 because it has no resources.
Nov 02 19:39:54 k3s-master k3s[4208]: W1102 19:39:54.599839    4208 genericapiserver.go:404] Skipping API apps/v1beta2 because it has no resources.
Nov 02 19:39:54 k3s-master k3s[4208]: W1102 19:39:54.599980    4208 genericapiserver.go:404] Skipping API apps/v1beta1 because it has no resources.
Nov 02 19:39:54 k3s-master k3s[4208]: I1102 19:39:54.664301    4208 plugins.go:158] Loaded 11 mutating admission controller(s) successfully in the following order: NamespaceLifecycle,LimitRanger,ServiceAccount,NodeRestriction,TaintNodesByCondition,Priority,DefaultTolerationSeconds,DefaultStorageClass,StorageObjectInUseProtection,MutatingAdmissionWebhook,RuntimeClass.
Nov 02 19:39:54 k3s-master k3s[4208]: I1102 19:39:54.664446    4208 plugins.go:161] Loaded 7 validating admission controller(s) successfully in the following order: LimitRanger,ServiceAccount,Priority,PersistentVolumeClaimResize,ValidatingAdmissionWebhook,RuntimeClass,ResourceQuota.
Nov 02 19:39:54 k3s-master k3s[4208]: time="2019-11-02T19:39:54.698695484Z" level=info msg="Running kube-scheduler --bind-address=127.0.0.1 --kubeconfig=/var/lib/rancher/k3s/server/cred/scheduler.kubeconfig --leader-elect=false --port=10251 --secure-port=0"
Nov 02 19:39:54 k3s-master k3s[4208]: time="2019-11-02T19:39:54.701758920Z" level=info msg="Running kube-controller-manager --allocate-node-cidrs=true --bind-address=127.0.0.1 --cluster-cidr=10.42.0.0/16 --cluster-signing-cert-file=/var/lib/rancher/k3s/server/tls/server-ca.crt --cluster-signing-key-file=/var/lib/rancher/k3s/server/tls/server-ca.key --kubeconfig=/var/lib/rancher/k3s/server/cred/controller.kubeconfig --leader-elect=false --port=10252 --root-ca-file=/var/lib/rancher/k3s/server/tls/server-ca.crt --secure-port=0 --service-account-private-key-file=/var/lib/rancher/k3s/server/tls/service.key --use-service-account-credentials=true"
Nov 02 19:39:54 k3s-master k3s[4208]: I1102 19:39:54.742162    4208 controllermanager.go:161] Version: v1.16.2-k3s.1
Nov 02 19:39:54 k3s-master k3s[4208]: I1102 19:39:54.745124    4208 deprecated_insecure_serving.go:53] Serving insecurely on [::]:10252
Nov 02 19:39:54 k3s-master k3s[4208]: I1102 19:39:54.748801    4208 server.go:143] Version: v1.16.2-k3s.1
Nov 02 19:39:54 k3s-master k3s[4208]: I1102 19:39:54.749420    4208 defaults.go:91] TaintNodesByCondition is enabled, PodToleratesNodeTaints predicate is mandatory
Nov 02 19:39:54 k3s-master k3s[4208]: W1102 19:39:54.755620    4208 authorization.go:47] Authorization is disabled
Nov 02 19:39:54 k3s-master k3s[4208]: W1102 19:39:54.755721    4208 authentication.go:79] Authentication is disabled
Nov 02 19:39:54 k3s-master k3s[4208]: I1102 19:39:54.755776    4208 deprecated_insecure_serving.go:51] Serving healthz insecurely on [::]:10251
Nov 02 19:40:04 k3s-master k3s[4208]: time="2019-11-02T19:40:04.724145807Z" level=fatal msg="starting tls server: Get https://127.0.0.1:6444/apis/apiextensions.k8s.io/v1beta1/customresourcedefinitions: net/http: TLS handshake timeout"
Nov 02 19:40:04 k3s-master systemd[1]: k3s.service: Main process exited, code=exited, status=1/FAILURE
Nov 02 19:40:04 k3s-master systemd[1]: k3s.service: Failed with result 'exit-code'.
Nov 02 19:40:04 k3s-master systemd[1]: Failed to start Lightweight Kubernetes.
-- Subject: Unit k3s.service has failed
```
 

**Describe the bug**
The k3s service fails immediately after installation `curl -sfL https://get.k3s.io | sh -`

**To Reproduce**
Get a Raspberry Pi 3 Model B install Rasbian Lite or Ubuntu server 18.04.3 ARMHF image.
run `curl -sfL https://get.k3s.io | sh -`
Service installation will fail

**Expected behavior**
Service k3s to run and k8s cluster to be up and running.

**Actual behavior**
k3s service fails. 
`149 deprecated_insecure_serving.go:51] Serving healthz insecurely on [::]:10251`

**Additional context**
I've tested with my Rasp Pi 4, 4GB model and works fine

**Comment by jfmatth** [comment] 2019-11-03 13:25
I'm having the same issue, even with the latest 0.10.2 release.

```
pi@k3s-master:~ $ uname -a
Linux k3s-master 4.19.75-v7+ #1270 SMP Tue Sep 24 18:45:11 BST 2019 armv7l GNU/Linux
pi@k3s-master:~ $ curl -sfL https://get.k3s.io | sh -
[INFO]  Finding latest release
[INFO]  Using v0.10.2 as release
[INFO]  Downloading hash https://github.com/rancher/k3s/releases/download/v0.10.2/sha256sum-arm.txt
[INFO]  Downloading binary https://github.com/rancher/k3s/releases/download/v0.10.2/k3s-armhf
[INFO]  Verifying binary download
[INFO]  Installing k3s to /usr/local/bin/k3s
[INFO]  Creating /usr/local/bin/kubectl symlink to k3s
[INFO]  Creating /usr/local/bin/crictl symlink to k3s
[INFO]  Creating /usr/local/bin/ctr symlink to k3s
[INFO]  Creating killall script /usr/local/bin/k3s-killall.sh
[INFO]  Creating uninstall script /usr/local/bin/k3s-uninstall.sh
[INFO]  env: Creating environment file /etc/systemd/system/k3s.service.env
[INFO]  systemd: Creating service file /etc/systemd/system/k3s.service
[INFO]  systemd: Enabling k3s unit
Created symlink /etc/systemd/system/multi-user.target.wants/k3s.service → /etc/systemd/system/k3s.service.
[INFO]  systemd: Starting k3s
Job for k3s.service failed because the control process exited with error code.
See "systemctl status k3s.service" and "journalctl -xe" for details.
pi@k3s-master:~ $ systemctl status k3s.service  -l
● k3s.service - Lightweight Kubernetes
   Loaded: loaded (/etc/systemd/system/k3s.service; enabled; vendor preset: enabled)
   Active: activating (start) since Sun 2019-11-03 13:24:36 GMT; 10s ago
     Docs: https://k3s.io
  Process: 1199 ExecStartPre=/sbin/modprobe br_netfilter (code=exited, status=0/SUCCESS)
  Process: 1200 ExecStartPre=/sbin/modprobe overlay (code=exited, status=0/SUCCESS)
 Main PID: 1201 (k3s-server)
    Tasks: 20
   Memory: 155.1M
   CGroup: /system.slice/k3s.service
           └─1201 /usr/local/bin/k3s server

Nov 03 13:24:40 k3s-master k3s[1201]: I1103 13:24:40.658133    1201 plugins.go:161] Loaded 7 validating admission controNov 03 13:24:40 k3s-master k3s[1201]: time="2019-11-03T13:24:40.694211700Z" level=info msg="Running kube-scheduler --binNov 03 13:24:40 k3s-master k3s[1201]: time="2019-11-03T13:24:40.697247528Z" level=info msg="Running kube-controller-manaNov 03 13:24:40 k3s-master k3s[1201]: I1103 13:24:40.741120    1201 controllermanager.go:161] Version: v1.16.2-k3s.1
Nov 03 13:24:40 k3s-master k3s[1201]: I1103 13:24:40.744373    1201 deprecated_insecure_serving.go:53] Serving insecurelNov 03 13:24:40 k3s-master k3s[1201]: I1103 13:24:40.747053    1201 server.go:143] Version: v1.16.2-k3s.1
Nov 03 13:24:40 k3s-master k3s[1201]: I1103 13:24:40.747503    1201 defaults.go:91] TaintNodesByCondition is enabled, PoNov 03 13:24:40 k3s-master k3s[1201]: W1103 13:24:40.754004    1201 authorization.go:47] Authorization is disabled
Nov 03 13:24:40 k3s-master k3s[1201]: W1103 13:24:40.754087    1201 authentication.go:79] Authentication is disabled
Nov 03 13:24:40 k3s-master k3s[1201]: I1103 13:24:40.754143    1201 deprecated_insecure_serving.go:51] Serving healthz ilines 1-22/22 (END)...skipping...
● k3s.service - Lightweight Kubernetes
   Loaded: loaded (/etc/systemd/system/k3s.service; enabled; vendor preset: enabled)
   Active: activating (start) since Sun 2019-11-03 13:24:36 GMT; 10s ago
     Docs: https://k3s.io
  Process: 1199 ExecStartPre=/sbin/modprobe br_netfilter (code=exited, status=0/SUCCESS)
  Process: 1200 ExecStartPre=/sbin/modprobe overlay (code=exited, status=0/SUCCESS)
 Main PID: 1201 (k3s-server)
    Tasks: 20
   Memory: 155.1M
   CGroup: /system.slice/k3s.service
           └─1201 /usr/local/bin/k3s server

Nov 03 13:24:40 k3s-master k3s[1201]: I1103 13:24:40.658133    1201 plugins.go:161] Loaded 7 validating admission controller(s) successfully in the following order:
Nov 03 13:24:40 k3s-master k3s[1201]: time="2019-11-03T13:24:40.694211700Z" level=info msg="Running kube-scheduler --bind-address=127.0.0.1 --kubeconfig=/var/lib/ran
Nov 03 13:24:40 k3s-master k3s[1201]: time="2019-11-03T13:24:40.697247528Z" level=info msg="Running kube-controller-manager --allocate-node-cidrs=true --bind-address
Nov 03 13:24:40 k3s-master k3s[1201]: I1103 13:24:40.741120    1201 controllermanager.go:161] Version: v1.16.2-k3s.1
Nov 03 13:24:40 k3s-master k3s[1201]: I1103 13:24:40.744373    1201 deprecated_insecure_serving.go:53] Serving insecurely on [::]:10252
Nov 03 13:24:40 k3s-master k3s[1201]: I1103 13:24:40.747053    1201 server.go:143] Version: v1.16.2-k3s.1
Nov 03 13:24:40 k3s-master k3s[1201]: I1103 13:24:40.747503    1201 defaults.go:91] TaintNodesByCondition is enabled, PodToleratesNodeTaints predicate is mandatory
Nov 03 13:24:40 k3s-master k3s[1201]: W1103 13:24:40.754004    1201 authorization.go:47] Authorization is disabled
Nov 03 13:24:40 k3s-master k3s[1201]: W1103 13:24:40.754087    1201 authentication.go:79] Authentication is disabled
Nov 03 13:24:40 k3s-master k3s[1201]: I1103 13:24:40.754143    1201 deprecated_insecure_serving.go:51] Serving healthz insecurely on [::]:10251
```

**Comment by Jurgen-Allewijn** [comment] 2019-11-04 13:32
I have the same issue with the same errors. Also with the version 0.10.2

**Comment by davidnuzik** [comment] 2019-11-04 16:18
Hello, this is a duplicate of https://github.com/rancher/k3s/issues/970 (TLS Handshake timeout error)
If there are errors unlike this let's open a separate issue please.

**Closed by davidnuzik** 2019-11-04 16:18 UTC
