### ISSUE TITLE
[QA] Validate Ubuntu 20.04

### ISSUE THREAD

**Issue by davidnuzik** [rancher/k3s#1712] opened 2020-04-29 15:25 UTC
QA to validate Ubuntu 20.04 against K3s. We will do this in v1.18; we may release v1.18.2 first then validate. We do not anticipate issues with v1.18.2 but currently it is technically not fully validated at this point.

If there are issues identified then the next v1.18 patch should claim support for Ubuntu 20.04.

**Comment by davidnuzik** [comment] 2020-05-15 18:22
Ships with nftables by default. 20.04 still has (x)tables - but we really should be using what OS is so this may work but isn't the best solution presently.

**Comment by brandond** [comment] 2020-05-15 19:38
FWIW, k3s v1.18.2 worked for me out of the box on a no-features install of 20.04 x86_64 server.

**Comment by davidnuzik** [comment] 2020-05-15 22:46
Yeah I think it should work fine OOTB there may be some edge cases / situations that might cause issues. It should get our suite of QA tests so we can bless it and officially support it. Longer term we want to set up a better solution for *tables.

**Comment by e3b0c442** [comment] 2020-05-18 00:49
k3s stable (v1.18.2+k3s1) does not work on Ubuntu 20.04 arm64 on a 4GB Raspberry Pi 4. Nothing is able to contact the kubernetes service, so the cluster doesn't come up cleanly. Clean image + documented firewall prerequisites, default install with no flags.

I'm working on trying against [18.04|20.04] [arm32/arm64] right now, to try and narrow down where the issue is; it worked fine on Raspbian Buster.

**Comment by e3b0c442** [comment] 2020-05-18 01:19
OK, I just tried the exact same on a clean Ubuntu 18.04 ARM64 server image and everything came right up, so whatever is going on is specific to Ubuntu 20.04.

I'm sorry I don't know exactly where to look next. I have another batch of RPi4s coming in this week to finish fitting out my cluster, when they arrive I'll be happy to hold one back to try turning up the server again on 20.04 and get whatever logs/info might help nail this down.

**Comment by weisjohn** [comment] 2020-05-18 04:49
Worked immediately for me tonight. My use-case might be helpful in testing?
I have a laptop from 2007 running Ubuntu 20.04 LTS, and joined it as a worker node to a Raspberry Pi 3+ master, also running [k3s on v1.18.2](https://github.com/rancher/k3s/releases/tag/v1.18.2%2Bk3s1).

@davidnuzik let me know if you want help testing anything.

**Comment by davidnuzik** [comment] 2020-05-18 17:12
@e3b0c442 Thanks for the info there that helps.
@weisjohn Thanks for the info as well. I will let you now if we'd like any help I appreciate that.

Mostly, what we need to do is go through dozens of test cases we have documented internally (we have a lot of automation but also have various manual tests in different environmental configurations).

Perhaps in the future these could be opened up but for now they are internal. Some things that can help are running k8s conformance tests (sonobuoy) on various architectures with Ubuntu 20.04 -- if anyone wants to give it a go :)  be mindful that on slow hardware sometimes things may fail especially armhf and sometimes arm64. Sometimes tests need to be re-tested to ensure not a fluke.

**Comment by erikwilson** [comment] 2020-05-18 17:21
afaik the k8s conformance tests only work on amd64 at the moment.

**Comment by weisjohn** [comment] 2020-05-22 03:45
Update: about 24 hours after I started the node it disappeared from the cluster, but the OS is still up and reachable on the network:

```
weisjohn@lamport:~$ sudo k3s check-config
[sudo] password for weisjohn:

Verifying binaries in /var/lib/rancher/k3s/data/572dcee7aa63e8f11e61142e4b0fc4f7ce33a0a6fed6a72924c6f6be85781b10/bin:
- sha256sum: good
- links: good

System:
- /usr/sbin iptables v1.8.4 (legacy): ok
- swap: should be disabled
- routes: default CIDRs 10.42.0.0/16 or 10.43.0.0/16 already routed

Limits:
- /proc/sys/kernel/keys/root_maxkeys: 1000000

modprobe: module configs not found in modules.dep
info: reading kernel config from /boot/config-5.4.0-29-generic ...

Generally Necessary:
- cgroup hierarchy: properly mounted [/sys/fs/cgroup]
- /usr/sbin/apparmor_parser
apparmor: enabled and tools installed
- CONFIG_NAMESPACES: enabled
- CONFIG_NET_NS: enabled
- CONFIG_PID_NS: enabled
- CONFIG_IPC_NS: enabled
- CONFIG_UTS_NS: enabled
- CONFIG_CGROUPS: enabled
- CONFIG_CGROUP_CPUACCT: enabled
- CONFIG_CGROUP_DEVICE: enabled
- CONFIG_CGROUP_FREEZER: enabled
- CONFIG_CGROUP_SCHED: enabled
- CONFIG_CPUSETS: enabled
- CONFIG_MEMCG: enabled
- CONFIG_KEYS: enabled
- CONFIG_VETH: enabled (as module)
- CONFIG_BRIDGE: enabled (as module)
- CONFIG_BRIDGE_NETFILTER: enabled (as module)
- CONFIG_NF_NAT_IPV4: missing (fail)
- CONFIG_IP_NF_FILTER: enabled (as module)
- CONFIG_IP_NF_TARGET_MASQUERADE: enabled (as module)
- CONFIG_NETFILTER_XT_MATCH_ADDRTYPE: enabled (as module)
- CONFIG_NETFILTER_XT_MATCH_CONNTRACK: enabled (as module)
- CONFIG_NETFILTER_XT_MATCH_IPVS: enabled (as module)
- CONFIG_IP_NF_NAT: enabled (as module)
- CONFIG_NF_NAT: enabled (as module)
- CONFIG_NF_NAT_NEEDED: missing (fail)
- CONFIG_POSIX_MQUEUE: enabled

Optional Features:
- CONFIG_USER_NS: enabled
- CONFIG_SECCOMP: enabled
- CONFIG_CGROUP_PIDS: enabled
- CONFIG_BLK_CGROUP: enabled
- CONFIG_BLK_DEV_THROTTLING: enabled
- CONFIG_CGROUP_PERF: enabled
- CONFIG_CGROUP_HUGETLB: enabled
- CONFIG_NET_CLS_CGROUP: enabled (as module)
- CONFIG_CGROUP_NET_PRIO: enabled
- CONFIG_CFS_BANDWIDTH: enabled
- CONFIG_FAIR_GROUP_SCHED: enabled
- CONFIG_RT_GROUP_SCHED: enabled
- CONFIG_IP_NF_TARGET_REDIRECT: enabled (as module)
- CONFIG_IP_SET: enabled (as module)
- CONFIG_IP_VS: enabled (as module)
- CONFIG_IP_VS_NFCT: enabled
- CONFIG_IP_VS_PROTO_TCP: enabled
- CONFIG_IP_VS_PROTO_UDP: enabled
- CONFIG_IP_VS_RR: enabled (as module)
- CONFIG_EXT4_FS: enabled
- CONFIG_EXT4_FS_POSIX_ACL: enabled
- CONFIG_EXT4_FS_SECURITY: enabled
- Network Drivers:
  - "overlay":
    - CONFIG_VXLAN: enabled (as module)
      Optional (for encrypted networks):
      - CONFIG_CRYPTO: enabled
      - CONFIG_CRYPTO_AEAD: enabled
      - CONFIG_CRYPTO_GCM: enabled
      - CONFIG_CRYPTO_SEQIV: enabled
      - CONFIG_CRYPTO_GHASH: enabled
      - CONFIG_XFRM: enabled
      - CONFIG_XFRM_USER: enabled (as module)
      - CONFIG_XFRM_ALGO: enabled (as module)
      - CONFIG_INET_ESP: enabled (as module)
      - CONFIG_INET_XFRM_MODE_TRANSPORT: missing
- Storage Drivers:
  - "overlay":
    - CONFIG_OVERLAY_FS: enabled (as module)

STATUS: 2 (fail)
```

**Comment by weisjohn** [comment] 2020-05-22 03:47
filtering the noise, the two red items are:
```
...
apparmor: enabled and tools installed
...
- CONFIG_NF_NAT_IPV4: missing (fail)
... 
- CONFIG_NF_NAT_NEEDED: missing (fail)
```

is there something I can do about those?

**Comment by brandond** [comment] 2020-05-22 08:08
@weisjohn those are noise as well. The kernel modules have been renamed but the check has not yet been updated to match. The system would not have functioned right for any period of time if they were missing.

Have you looked at the logs yet?

**Comment by weisjohn** [comment] 2020-05-23 17:11
@brandond 
> The system would not have functioned right for any period of time if they were missing.
Good to know, that's what I was thinking too.

> What do you mean by disappeared. Does it no longer show up in kubectl get nodes at all?

Sorry for using "disappeared". More accurately, the node's status was NotReady. And now it's back, (lamport is the node that went NotReady):

```
λ kubectl get nodes
NAME      STATUS   ROLES    AGE     VERSION
shannon   Ready    master   5d14h   v1.18.2+k3s1
lamport   Ready    node     5d13h   v1.18.2+k3s1
```

```
$ kubectl describe nodes lamport
Name:               lamport
Roles:              node
Labels:             beta.kubernetes.io/arch=amd64
                    beta.kubernetes.io/instance-type=k3s
                    beta.kubernetes.io/os=linux
                    k3s.io/hostname=lamport
                    k3s.io/internal-ip=10.0.0.21
                    kubernetes.io/arch=amd64
                    kubernetes.io/hostname=lamport
                    kubernetes.io/os=linux
                    node-role.kubernetes.io/node=node
                    node.kubernetes.io/instance-type=k3s
Annotations:        flannel.alpha.coreos.com/backend-data: {"VtepMAC":"26:94:74:75:11:3a"}
                    flannel.alpha.coreos.com/backend-type: vxlan
                    flannel.alpha.coreos.com/kube-subnet-manager: true
                    flannel.alpha.coreos.com/public-ip: 10.0.0.21
                    k3s.io/node-args: ["agent"]
                    k3s.io/node-config-hash: EKSNX6RAKYQUAL2FPXBXQMWFC7DYB5BL6SPQPHJRUV2R6HQU3B2Q====
                    k3s.io/node-env:
                      {"K3S_DATA_DIR":"/var/lib/rancher/k3s/data/572dcee7aa63e8f11e61142e4b0fc4f7ce33a0a6fed6a72924c6f6be85781b10","K3S_TOKEN":"********","K3S_U...
                    node.alpha.kubernetes.io/ttl: 0
                    volumes.kubernetes.io/controller-managed-attach-detach: true
CreationTimestamp:  Sun, 17 May 2020 23:07:14 -0400
Taints:             <none>
Unschedulable:      false
Lease:
  HolderIdentity:  lamport
  AcquireTime:     <unset>
  RenewTime:       Sat, 23 May 2020 12:59:04 -0400
Conditions:
  Type                 Status  LastHeartbeatTime                 LastTransitionTime                Reason                       Message
  ----                 ------  -----------------                 ------------------                ------                       -------
  NetworkUnavailable   False   Sun, 17 May 2020 23:11:00 -0400   Sun, 17 May 2020 23:11:00 -0400   FlannelIsUp                  Flannel is running on this node
  MemoryPressure       False   Sat, 23 May 2020 12:55:32 -0400   Mon, 18 May 2020 18:36:26 -0400   KubeletHasSufficientMemory   kubelet has sufficient memory available
  DiskPressure         False   Sat, 23 May 2020 12:55:32 -0400   Mon, 18 May 2020 18:36:26 -0400   KubeletHasNoDiskPressure     kubelet has no disk pressure
  PIDPressure          False   Sat, 23 May 2020 12:55:32 -0400   Mon, 18 May 2020 18:36:26 -0400   KubeletHasSufficientPID      kubelet has sufficient PID available
  Ready                True    Sat, 23 May 2020 12:55:32 -0400   Mon, 18 May 2020 18:36:26 -0400   KubeletReady                 kubelet is posting ready status. AppArmor enabled
Addresses:
  InternalIP:  10.0.0.21
  Hostname:    lamport
Capacity:
  cpu:                2
  ephemeral-storage:  150511256Ki
  hugepages-2Mi:      0
  memory:             3963832Ki
  pods:               110
Allocatable:
  cpu:                2
  ephemeral-storage:  146417349722
  hugepages-2Mi:      0
  memory:             3963832Ki
  pods:               110
System Info:
  Machine ID:                 320ef35cf2344b21a849252e7f9c42fe
  System UUID:                ca97f901-495b-11cb-92be-f75ae18d1493
  Boot ID:                    5fac84dc-5b28-4335-aad1-3a11503dac5d
  Kernel Version:             5.4.0-29-generic
  OS Image:                   Ubuntu 20.04 LTS
  Operating System:           linux
  Architecture:               amd64
  Container Runtime Version:  containerd://1.3.3-k3s2
  Kubelet Version:            v1.18.2+k3s1
  Kube-Proxy Version:         v1.18.2+k3s1
PodCIDR:                      10.42.1.0/24
PodCIDRs:                     10.42.1.0/24
ProviderID:                   k3s://lamport
Non-terminated Pods:          (1 in total)
  Namespace                   Name                   CPU Requests  CPU Limits  Memory Requests  Memory Limits  AGE
  ---------                   ----                   ------------  ----------  ---------------  -------------  ---
  kube-system                 svclb-traefik-lzb49    0 (0%)        0 (0%)      0 (0%)           0 (0%)         5d13h
Allocated resources:
  (Total limits may be over 100 percent, i.e., overcommitted.)
  Resource           Requests  Limits
  --------           --------  ------
  cpu                0 (0%)    0 (0%)
  memory             0 (0%)    0 (0%)
  ephemeral-storage  0 (0%)    0 (0%)
  hugepages-2Mi      0 (0%)    0 (0%)
Events:              <none>
```

AFAIK, I was always able to access the OS through ssh during the NotReady period and the machine didn't reboot or suspend:

```
λ ssh lamport
weisjohn@lamport:~$ uptime
 13:01:11 up 5 days, 15:32,  2 users,  load average: 0.09, 0.04, 0.01
```

At the time it went NotReady, I was running a Deployment based on https://github.com/GoogleCloudPlatform/kubernetes-engine-samples/blob/master/hello-app/manifests/helloweb-deployment.yaml for test purposes w/ 10 desired replicas. They all were successfully scheduled against that node.... 

But it actually looks like the master node (shannon) moved on my network from 10.0.0.59 to 10.0.020:

```
weisjohn@lamport:~$ journalctl -u k3s
May 17 21:34:08 lamport k3s[848]: I0517 21:34:08.479759     848 request.go:621] Throttling request took 1.046979582s, request: GET:https://127.0.0.1:6444/apis/rbac.authorization.k8s.io/v1?timeout=32s
May 17 21:34:08 lamport k3s[848]: time="2020-05-17T21:34:08.830122974-04:00" level=info msg="Connecting to proxy" url="wss://10.0.0.59:6443/v1-k3s/connect"
May 17 21:34:09 lamport k3s[848]: W0517 21:34:09.231626     848 garbagecollector.go:644] failed to discover some groups: map[metrics.k8s.io/v1beta1:the server is currently unable to handle the request]
May 17 21:34:10 lamport k3s[848]: time="2020-05-17T21:34:10.389760469-04:00" level=error msg="Failed to connect to proxy" error="dial tcp 10.0.0.59:6443: connect: no route to host"
May 17 21:34:10 lamport k3s[848]: time="2020-05-17T21:34:10.389870608-04:00" level=error msg="Remotedialer proxy error" error="dial tcp 10.0.0.59:6443: connect: no route to host"
May 17 21:34:15 lamport k3s[848]: time="2020-05-17T21:34:15.390159896-04:00" level=info msg="Connecting to proxy" url="wss://10.0.0.59:6443/v1-k3s/connect"
May 17 21:34:16 lamport k3s[848]: time="2020-05-17T21:34:16.917871741-04:00" level=error msg="Failed to connect to proxy" error="dial tcp 10.0.0.59:6443: connect: no route to host"
May 17 21:34:16 lamport k3s[848]: time="2020-05-17T21:34:16.918025811-04:00" level=error msg="Remotedialer proxy error" error="dial tcp 10.0.0.59:6443: connect: no route to host"
May 17 21:34:21 lamport k3s[848]: time="2020-05-17T21:34:21.918356062-04:00" level=info msg="Connecting to proxy" url="wss://10.0.0.59:6443/v1-k3s/connect"
May 17 21:34:23 lamport k3s[848]: time="2020-05-17T21:34:23.445776021-04:00" level=error msg="Failed to connect to proxy" error="dial tcp 10.0.0.59:6443: connect: no route to host"
May 17 21:34:23 lamport k3s[848]: time="2020-05-17T21:34:23.445868072-04:00" level=error msg="Remotedialer proxy error" error="dial tcp 10.0.0.59:6443: connect: no route to host"
May 17 21:34:26 lamport k3s[848]: E0517 21:34:26.090926     848 available_controller.go:420] v1beta1.metrics.k8s.io failed with: failing or missing response from https://10.43.62.2:443/apis/metrics.k8s.io/v1beta1: Get https://10.43.62.>
May 17 21:34:26 lamport systemd[1]: Stopping Lightweight Kubernetes...
May 17 21:34:26 lamport k3s[848]: I0517 21:34:26.170858     848 network_policy_controller.go:173] Shutting down network policies controller
May 17 21:34:26 lamport k3s[848]: time="2020-05-17T21:34:26.172522330-04:00" level=info msg="Shutting down k3s.cattle.io/v1, Kind=Addon workers"
May 17 21:34:26 lamport k3s[848]: time="2020-05-17T21:34:26.173488100-04:00" level=error msg="Tunnel endpoint watch channel closed: {ERROR &Status{ListMeta:ListMeta{SelfLink:,ResourceVersion:,Continue:,RemainingItemCount:nil,},Status:F>
May 17 21:34:26 lamport k3s[848]: I0517 21:34:26.176852     848 controller.go:185] Shutting down kubernetes service endpoint reconciler
May 17 21:34:26 lamport k3s[848]: I0517 21:34:26.177186     848 controller.go:87] Shutting down OpenAPI AggregationController
May 17 21:34:26 lamport k3s[848]: I0517 21:34:26.179267     848 controller.go:123] Shutting down OpenAPI controller
May 17 21:34:26 lamport k3s[848]: I0517 21:34:26.179681     848 apiapproval_controller.go:198] Shutting down KubernetesAPIApprovalPolicyConformantConditionController
May 17 21:34:26 lamport k3s[848]: I0517 21:34:26.180060     848 nonstructuralschema_controller.go:198] Shutting down NonStructuralSchemaConditionController
May 17 21:34:26 lamport k3s[848]: I0517 21:34:26.180494     848 establishing_controller.go:87] Shutting down EstablishingController
May 17 21:34:26 lamport k3s[848]: I0517 21:34:26.180547     848 naming_controller.go:302] Shutting down NamingConditionController
May 17 21:34:26 lamport k3s[848]: I0517 21:34:26.180591     848 customresource_discovery_controller.go:220] Shutting down DiscoveryController
May 17 21:34:26 lamport k3s[848]: I0517 21:34:26.180636     848 crdregistration_controller.go:142] Shutting down crd-autoregister controller
May 17 21:34:26 lamport k3s[848]: I0517 21:34:26.180681     848 apiservice_controller.go:106] Shutting down APIServiceRegistrationController
May 17 21:34:26 lamport k3s[848]: I0517 21:34:26.180725     848 autoregister_controller.go:165] Shutting down autoregister controller
May 17 21:34:26 lamport k3s[848]: I0517 21:34:26.180770     848 available_controller.go:399] Shutting down AvailableConditionController
May 17 21:34:26 lamport k3s[848]: I0517 21:34:26.180833     848 cluster_authentication_trust_controller.go:463] Shutting down cluster_authentication_trust_controller controller
May 17 21:34:26 lamport k3s[848]: I0517 21:34:26.180875     848 crd_finalizer.go:278] Shutting down CRDFinalizer
May 17 21:34:26 lamport k3s[848]: I0517 21:34:26.183056     848 dynamic_cafile_content.go:182] Shutting down request-header::/var/lib/rancher/k3s/server/tls/request-header-ca.crt
May 17 21:34:26 lamport k3s[848]: I0517 21:34:26.183107     848 dynamic_cafile_content.go:182] Shutting down client-ca-bundle::/var/lib/rancher/k3s/server/tls/client-ca.crt
May 17 21:34:26 lamport k3s[848]: I0517 21:34:26.183308     848 dynamic_cafile_content.go:182] Shutting down request-header::/var/lib/rancher/k3s/server/tls/request-header-ca.crt
May 17 21:34:26 lamport k3s[848]: I0517 21:34:26.184345     848 tlsconfig.go:255] Shutting down DynamicServingCertificateController
May 17 21:34:26 lamport k3s[848]: I0517 21:34:26.184394     848 dynamic_serving_content.go:145] Shutting down serving-cert::/var/lib/rancher/k3s/server/tls/serving-kube-apiserver.crt::/var/lib/rancher/k3s/server/tls/serving-kube-apiser>
May 17 21:34:26 lamport k3s[848]: I0517 21:34:26.184477     848 dynamic_cafile_content.go:182] Shutting down client-ca-bundle::/var/lib/rancher/k3s/server/tls/client-ca.crt
May 17 21:34:26 lamport k3s[848]: time="2020-05-17T21:34:26.196944741-04:00" level=fatal msg="server stopped: http: Server closed"
May 17 21:34:26 lamport systemd[1]: k3s.service: Main process exited, code=exited, status=1/FAILURE
May 17 21:34:26 lamport systemd[1]: k3s.service: Failed with result 'exit-code'.
May 17 21:34:26 lamport systemd[1]: Stopped Lightweight Kubernetes.
```

The node must have come back on it's own, as I connected to the master via local hostname-based DNS,  not IP addresses. So, it was probably just a problem with DNS cache.

Thanks for the help, and sorry for the noise.

**Comment by radum** [comment] 2020-05-30 22:00
I can confirm also what @e3b0c442 said. k3s stable (v1.18.2+k3s1) does not work on Ubuntu 20.04 arm64 on a 4GB Raspberry Pi 4.

`Error from server (ServiceUnavailable): the server is currently unable to handle the request`

**Comment by ShylajaDevadiga** [comment] 2020-06-02 23:46
@radum Arm64 validation will be tracked in this issue https://github.com/rancher/k3s/issues/1860
Closing issue as validation of K3s cluster using Ubuntu20.04 on amd64 is complete.

**Closed by ShylajaDevadiga** 2020-06-02 23:46 UTC
Labels: [zube]: Working, kind/task
