### ISSUE TITLE
High disk usage on external datastore (mysql)

### ISSUE THREAD

**Issue by rdelcorro** [rancher/k3s#1311] opened 2020-01-18 19:18 UTC
**Version:**
k3s version v1.0.1 (e94a3c60)

**Describe the bug**
The external datastore usage is too high while nothing is being deployed in the cluster except the base containers

**To Reproduce**
Run a cluster with two masters and two workers connected to a single mysql database

**Expected behavior**
Database should not grow indefinitely 

**Actual behavior**
K3s is adding 5 rows per second, causing the entire cluster to fail when the datastore is full

**Additional context**
Is there a way to limit the size of the external datastore? I do see that the kine table has binary blobs on each row and its currently around 2M rows with approx 2G of disk used. The cluster is for home use, running on a PI 4 and 3 x86 VMs in esxi. 

gz#13041

gz#12889

**Comment by jhughes2112** [comment] 2020-06-08 23:36
Oh my g*d, please fix this.  I just set up a HA cluster of k3s to manage a set of servers.  20gb RDS instance was full in 9 days.  For future reference, when AWS RDS servers get full, k3s fails by giving the MySQL "Too Many Connections" 1040 error .

**Comment by brandond** [comment] 2020-06-08 23:58
I have a sneaking suspicion that the compact code isn't actually deleting rows, or it's not auto-compacting periodically like etcd does. Haven't had a chance to confirm this personally though.

**Comment by jhughes2112** [comment] 2020-06-09 04:23
```
mysql> SELECT table_schema AS "Database",
    -> ROUND(SUM(data_length + index_length) / 1024 / 1024, 2) AS "Size (MB)"
    -> FROM information_schema.TABLES
    -> GROUP BY table_schema;
+--------------------+-----------+
| Database           | Size (MB) |
+--------------------+-----------+
| information_schema |      0.19 |
| k3s                |  17612.11 |
| mysql              |      7.71 |
| performance_schema |      0.00 |
| sys                |      0.02 |
+--------------------+-----------+

mysql> SELECT * FROM INFORMATION_SCHEMA.STATISTICS   WHERE table_name = 'kine'   AND table_schema = 'k3s';
+---------------+--------------+------------+------------+--------------+--------------------------------+--------------+---------------+-----------+-------------+----------+--------+----------+------------+---------+---------------+
| TABLE_CATALOG | TABLE_SCHEMA | TABLE_NAME | NON_UNIQUE | INDEX_SCHEMA | INDEX_NAME                     | SEQ_IN_INDEX | COLUMN_NAME   | COLLATION | CARDINALITY | SUB_PART | PACKED | NULLABLE | INDEX_TYPE | COMMENT | INDEX_COMMENT |
+---------------+--------------+------------+------------+--------------+--------------------------------+--------------+---------------+-----------+-------------+----------+--------+----------+------------+---------+---------------+
| def           | k3s          | kine       |          0 | k3s          | PRIMARY                        |            1 | id            | A         |     2464515 |     NULL | NULL   |          | BTREE      |         |               |
| def           | k3s          | kine       |          0 | k3s          | kine_name_prev_revision_uindex |            1 | name          | A         |       39438 |     NULL | NULL   | YES      | BTREE      |         |               |
| def           | k3s          | kine       |          0 | k3s          | kine_name_prev_revision_uindex |            2 | prev_revision | A         |     2372992 |     NULL | NULL   | YES      | BTREE      |         |               |
| def           | k3s          | kine       |          1 | k3s          | kine_name_index                |            1 | name          | A         |       38317 |     NULL | NULL   | YES      | BTREE      |         |               |
| def           | k3s          | kine       |          1 | k3s          | kine_name_id_index             |            1 | name          | A         |       21220 |     NULL | NULL   | YES      | BTREE      |         |               |
| def           | k3s          | kine       |          1 | k3s          | kine_name_id_index             |            2 | id            | A         |     2358582 |     NULL | NULL   |          | BTREE      |         |               |
+---------------+--------------+------------+------------+--------------+--------------------------------+--------------+---------------+-----------+-------------+----------+--------+----------+------------+---------+---------------+
```
I have noticed there are some gaps in the `id` index range, so I suspect SOME things are being deleted.  But if any ONE thing does not get deleted when it should, you will always have runaway growth in a database-driven system like this.  From what little visual inspection I could give it, deleted is almost always 0 (because those items didn't get deleted, presumably), and lease seems to also be 0 most of the time.
```
| id      | name        | created | deleted | create_revision | prev_revision | lease | value | old_value |
+---------+-------------+---------+---------+-----------------+---------------+-------+-------+-----------+
| 7756945 | gap-7756945 |       0 |       1 |               0 |             0 |     0 | NULL  | NULL      |
```
This entry is suspiciously the first one that is marked deleted.  Doesn't look to have much data to speak of, so ok...  but then it looks like it gets into a cycle and nothing is ever marked to be deleted:
```
| 7756996 | /registry/configmaps/kube-system/cattle-controllers                 |       0 |       0 |            3732 |       7756984 |     0 |
| 7756997 | /registry/services/endpoints/kube-system/rancher.io-local-path      |       0 |       0 |             499 |       7756985 |     0 |
| 7756998 | /registry/masterleases/172.31.20.187                                |       0 |       0 |         4731773 |       7756943 |    15 |
| 7756999 | /registry/management.cattle.io/listenconfigs/cli-config             |       0 |       0 |            3742 |       7756987 |     0 |
| 7757000 | /registry/services/endpoints/kube-system/kube-controller-manager    |       0 |       0 |             150 |       7756988 |     0 |
| 7757001 | /registry/services/endpoints/kube-system/kube-scheduler             |       0 |       0 |             161 |       7756989 |     0 |
| 7757002 | /registry/configmaps/cert-manager/cert-manager-controller           |       0 |       0 |           17930 |       7756917 |     0 |
| 7757003 | /registry/configmaps/kube-system/k3s                                |       0 |       0 |             168 |       7756992 |     0 |
| 7757004 | /registry/leases/kube-system/kube-scheduler                         |       0 |       0 |             162 |       7756990 |     0 |
| 7757005 | /registry/leases/kube-system/kube-controller-manager                |       0 |       0 |             152 |       7756991 |     0 |
| 7757006 | /registry/services/endpoints/kube-system/cloud-controller-manager   |       0 |       0 |             200 |       7756993 |     0 |
| 7757007 | /registry/leases/kube-system/cloud-controller-manager               |       0 |       0 |             202 |       7756994 |     0 |
| 7757008 | /registry/masterleases/172.31.14.105                                |       0 |       0 |         4729530 |       7756953 |    15 |
| 7757009 | /registry/configmaps/cert-manager/controller-leader-election-helper |       0 |       0 |           17972 |       7756995 |     0 |
| 7757010 | /registry/configmaps/kube-system/cattle-controllers                 |       0 |       0 |            3732 |       7756996 |     0 |
| 7757011 | /registry/services/endpoints/kube-system/rancher.io-local-path      |       0 |       0 |             499 |       7756997 |     0 |
| 7757012 | /registry/leases/kube-node-lease/ip-172-31-14-105                   |       0 |       0 |             741 |       7756954 |     0 |
| 7757013 | /registry/leases/kube-node-lease/ip-172-31-11-178                   |       0 |       0 |             261 |       7756958 |     0 |
| 7757014 | /registry/configmaps/kube-system/k3s                                |       0 |       0 |             168 |       7757003 |     0 |
| 7757015 | /registry/management.cattle.io/listenconfigs/cli-config             |       0 |       0 |            3742 |       7756999 |     0 |
| 7757016 | /registry/services/endpoints/kube-system/kube-controller-manager    |       0 |       0 |             150 |       7757000 |     0 |
| 7757017 | /registry/services/endpoints/kube-system/kube-scheduler             |       0 |       0 |             161 |       7757001 |     0 |
| 7757018 | /registry/leases/kube-system/kube-controller-manager                |       0 |       0 |             152 |       7757005 |     0 |
| 7757019 | /registry/leases/kube-system/kube-scheduler                         |       0 |       0 |             162 |       7757004 |     0 |
| 7757020 | /registry/services/endpoints/kube-system/cloud-controller-manager   |       0 |       0 |             200 |       7757006 |     0 |
| 7757021 | /registry/leases/kube-system/cloud-controller-manager               |       0 |       0 |             202 |       7757007 |     0 |
| 7757022 | /registry/configmaps/cert-manager/controller-leader-election-helper |       0 |       0 |           17972 |       7757009 |     0 |
| 7757023 | /registry/configmaps/kube-system/cattle-controllers                 |       0 |       0 |            3732 |       7757010 |     0 |
| 7757024 | /registry/services/endpoints/kube-system/rancher.io-local-path      |       0 |       0 |             499 |       7757011 |     0 |
| 7757025 | /registry/configmaps/kube-system/k3s                                |       0 |       0 |             168 |       7757014 |     0 |
```

I hope this helps track it down.  For the time being, I suspect I'll nuke the HA rancher cluster and go back to using a single docker instance.

**Comment by jhughes2112** [comment] 2020-06-09 04:26
k3s version v1.18.3+k3s1 (96653e8d)

**Comment by brandond** [comment] 2020-06-09 07:02
kine's handling of events with TTLs is interesting and has caused problems in the past, see https://github.com/rancher/k3s/issues/1628. I can't think of any reason off the top of my head why it would stop deleting things but honestly the ttl stuff could use a bit of a rewrite as well as some metrics and logging added.

**Comment by jhughes2112** [comment] 2020-06-09 13:54
Just guessing, but if kine does something dumb like make a new db connection per event, the moment it starts running a query (like delete?) That takes longer than the rate of its average event, it would result in a connection overflow in MySQL, which would eventually cause exceptions on connect.  A slow query log would show if this were the case.

**Comment by brandond** [comment] 2020-06-18 08:12
k3s already logs any etcd operation that takes over 500ms. This includes etcd operations against kine. If you're seeing slow queries you should already know about it.

I'm still curious what caused your DB to fill. I've been running my cluster for a couple days and it's reached a steady state of only 400 MB on disk, most of which is binlog - the k3s table itself is about 18mb. I've crashed k3s many times due to other issues and haven't gotten it into the same weird state you ran into.

**Comment by jhughes2112** [comment] 2020-06-18 13:21
It might be something related to the performance of the etcd itself.  The machines this was running on were booting USB and data was on nvme but I didn't realize I missed moving /var/lib/etcd to the nvme drive.  That made performance pretty spotty.  I did see the etcd raft re-elect every few seconds continuously--thought that was normal.  I am guessing running on slow hardware would repro the bug quickly.

From the data I clipped up above, someone should be able to tell what isn't being deleted from the MySQL table, either way though.  I strongly doubt it was generating that many unique keys, or all etcd instances would experience heavy growth over time. 
My thought is either there's a bug in the code that's figuring out what to delete, or when the performance gets too low it fails to delete anymore.

**Comment by jhughes2112** [comment] 2020-06-18 13:27
Dunno.  That particular cluster was on AWS and the etcd external MySQL was in RDS.  There was no load on it, and looked like etcd was re-electing constantly.  Three nodes in the etcd cluster, all workers and control planes.  I didn't see anything else worth mentioning.

In any case, based on the table data I clipped above, it wasn't immediate that it stopped deleting things, but once it hit some moment in time, the system began a runaway train and looks like nothing got deleted.  Probably when performance degraded enough, or the work to figure out what to delete became large enough that the garbage collector failed.  Dunno.

**Comment by brandond** [comment] 2020-06-18 17:53
The fact that you have a gap entry is interesting. That indicates that at some point it got rows out of order from the database, which shouldn't happen.

https://github.com/rancher/kine/blob/master/pkg/logstructured/sqllog/sql.go#L395

**Comment by liyongxian** [comment] 2020-06-20 07:52
**I met the same Issue,and logs info:**

Jun 20 15:46:57 k3s-server-2 k3s[60897]: time="2020-06-20T15:46:57.205394522+08:00" level=error msg="failed to record compact revision: rpc error: **code = InvalidArgument desc = etcdserver: duplicate key given in txn request**"
Jun 20 15:47:02 k3s-server-2 k3s[60897]: I0620 15:47:02.410003   60897 controller.go:107] OpenAPI AggregationController: Processing item v1beta1.metrics.k8s.io
Jun 20 15:48:02 k3s-server-2 k3s[60897]: I0620 15:48:02.412822   60897 controller.go:107] OpenAPI AggregationController: Processing item v1beta1.metrics.k8s.io
Jun 20 15:49:02 k3s-server-2 k3s[60897]: I0620 15:49:02.415616   60897 controller.go:107] OpenAPI AggregationController: Processing item v1beta1.metrics.k8s.io
Jun 20 15:49:20 k3s-server-2 k3s[60897]: I0620 15:49:20.495968   60897 trace.go:116] Trace[1626288055]: "GuaranteedUpdate etcd3" type:*coordination.Lease (started: 2020-06-20 15:49:19.794041124 +0800 CST m=+443.468107042) (total time: 701.89255ms):
Jun 20 15:49:20 k3s-server-2 k3s[60897]: Trace[1626288055]: [701.859503ms] [701.668786ms] Transaction committed
Jun 20 15:49:20 k3s-server-2 k3s[60897]: I0620 15:49:20.496089   60897 trace.go:116] Trace[1354703816]: "Update" url:/apis/coordination.k8s.io/v1/namespaces/kube-node-lease/leases/k3s-server-2,user-agent:k3s/v1.17.2+k3s1 (linux/amd64) kubernetes/cdab19b,client:127.0.0.1 (started: 2020-06-20 15:49:19.793941504 +0800 CST m=+443.468007404) (total time: 702.12409ms):
Jun 20 15:49:20 k3s-server-2 k3s[60897]: Trace[1354703816]: [702.067892ms] [702.001414ms] Object stored in database
Jun 20 15:49:20 k3s-server-2 k3s[60897]: I0620 15:49:20.497928   60897 trace.go:116] Trace[308083758]: "GuaranteedUpdate etcd3" type:*core.Endpoints (started: 2020-06-20 15:49:19.990499588 +0800 CST m=+443.664565504) (total time: 507.405602ms):
Jun 20 15:49:20 k3s-server-2 k3s[60897]: Trace[308083758]: [507.387529ms] [507.164118ms] Transaction committed
Jun 20 15:49:20 k3s-server-2 k3s[60897]: I0620 15:49:20.498036   60897 trace.go:116] Trace[758301186]: "Update" url:/api/v1/namespaces/kube-system/endpoints/rancher.io-local-path,user-agent:local-path-provisioner/v0.0.0 (linux/amd64) kubernetes/$Format,client:192.168.66.224 (started: 2020-06-20 15:49:19.99037777 +0800 CST m=+443.664443653) (total time: 507.639602ms):
Jun 20 15:49:20 k3s-server-2 k3s[60897]: Trace[758301186]: [507.581156ms] [507.491697ms] Object stored in database
Jun 20 15:50:02 k3s-server-2 k3s[60897]: I0620 15:50:02.418827   60897 controller.go:107] OpenAPI AggregationController: Processing item v1beta1.metrics.k8s.io
Jun 20 15:51:02 k3s-server-2 k3s[60897]: I0620 15:51:02.424565   60897 controller.go:107] OpenAPI AggregationController: Processing item v1beta1.metrics.k8s.io
Jun 20 15:51:57 k3s-server-2 k3s[60897]: time="2020-06-20T15:51:57.108917160+08:00" level=error msg="failed to record compact revision: rpc error: code = InvalidArgument desc = etcdserver: duplicate key given in txn request"
Jun 20 15:52:02 k3s-server-2 k3s[60897]: I0620 15:52:02.427510   60897 controller.go:107] OpenAPI AggregationController: Processing item v1beta1.metrics.k8s.io

**Comment by brandond** [comment] 2020-06-20 23:19
@liyongxian what database are you using for your datastore? Is it self hosted, and if so on what sort of disk/cpu? If you are using a hosting provider, which one and what resources has it been allocated?

**Comment by liyongxian** [comment] 2020-06-22 01:26
@brandond  
**mysql --version**
Ver 15.1 Distrib 10.2.32-MariaDB, for debian-linux-gnu (x86_64) using readline 5.2
**top**
![top](https://user-images.githubusercontent.com/18571576/85240191-c8b39700-b469-11ea-9236-a1d08ef40402.jpg)
**OS**
Ubuntu 16.04.1 LTS  4.4.0-184-generic
**Resource Allocated**
2 C /4 G.
Thanks.

**Comment by liyongxian** [comment] 2020-06-22 01:32
@brandond  For two days,the Kine table increases 993040 rows.
![kine](https://user-images.githubusercontent.com/18571576/85240612-5348c600-b46b-11ea-891f-d67555c71fb9.jpg)

**Comment by liyongxian** [comment] 2020-06-22 08:01
table  kine statistical info:
![resource](https://user-images.githubusercontent.com/18571576/85263263-7db57600-b4a1-11ea-89d3-3c9fc38ba6ec.jpg)
Do Not Know Why.
Thanks.

**Comment by brandond** [comment] 2020-06-22 19:19
Those are all things that get touched constantly since they're used for leader election. 

There's definitely something broken with compaction based on this error:
`level=error msg="failed to record compact revision: rpc error: code = InvalidArgument desc = etcdserver: duplicate key given in txn request"`. It almost sounds as if you somehow have multiple `compact_rev_key` entries and the update to record the new compact revision is causing a constraint violation on the ` kine_name_prev_revision_uindex` index?

Can you share the output of:
```sql
SELECT * FROM kine WHERE name = 'compact_rev_key';
```

**Comment by brandond** [comment] 2020-06-22 21:46
FWIW, I was able to hose my database similar to what's reported here by creating a duplicate `compact_rev_key` entry that pointed to a range partway through the existing entries.

I didn't see any duplicate key errors, and the oldest `compact_rev_key` entry was was removed when I restarted k3s, but I now have several hundred thousand 'gap' entries, and old revisions are not being compacted.

**Comment by liyongxian** [comment] 2020-06-23 01:31
@brandond  Thanks for your reply.
The Result of Executing SQL :
![compact_rev_key](https://user-images.githubusercontent.com/18571576/85350595-1b598580-b534-11ea-8a05-80231dffc53b.jpg)

**Comment by liyongxian** [comment] 2020-06-23 01:55
@brandond  I am confused by some questions:
1.What **compact_rev_key** means,Or how can it works,  when was its entry deleted.
2. Why  K3s generates  Duplicate key of compact_rev_key .
3. Why K3s  generate many **gap** rows ,  what **gap**  means.
Thanks.

**Comment by liyongxian** [comment] 2020-06-23 02:05
K3s generate many LeaderElection events.
![leaderElection](https://user-images.githubusercontent.com/18571576/85352644-ff0c1780-b538-11ea-842f-54ff88021e37.jpg)

**Comment by brandond** [comment] 2020-06-23 06:03
Kine makes a SQL datastore act like etcd. Each row in the database is like a revision to the etcd datastore, occasionally it compacts the datastore by cleaning up old entries and marks the point it compacted up to by storing it in the special compact_rev_key entry. There should only ever be one key with this name, and usually it is created very early and has a low id. The fact that you have two entries with high id numbers that are compacted up to within a revision of each
other suggests something went pretty wrong. Perhaps some sort of race condition when multiple nodes come up at the same time?

The gaps are created as dummy entries when it finds rows out of sequence or when the sequence skips forward during compaction, which shouldn't happen. It's supposed to help fix things but I don't think it's actually working.

**Comment by liyongxian** [comment] 2020-06-23 08:52
@brandond  Thanks.
These problems are caused by K3s or Kine? I think it is a bug. It can cause high system load , seriously effects the nomal use of K3s. 
I  can delete one row of  **compact_rev_key**?

**Comment by liyongxian** [comment] 2020-06-23 10:37
When I start K3s**,ESTABLISHED** increase too many at shot time.
![mysql](https://user-images.githubusercontent.com/18571576/85394005-82049080-b580-11ea-806d-824850aa3c96.jpg)

**Comment by brandond** [comment] 2020-06-23 17:35
Kine is a part of k3s. Lots of folks run multi-master k3s successfully against an external SQL datastore, but there are definitely some corner cases that it doesn't seem to handle well just yet.

I'm not sure what you're demonstrating with the netstat output. k3s does open a lot of connections, both to the datastore and between internal components. That is expected.

**Comment by haydnhkim** [comment] 2020-07-29 19:07
In my case, a problem occurred when `CrashLoopBackOff` occurred in the pod that was abnormally terminated.
start -> crash -> start -> crash The logs were continuously generated, and this problem occupied about 20GB in 2 weeks.

Specification
MySQL: 8.0.20
k3s: v1.18.4+k3s1
hosting: Bare metal
CPU: 2vCore
RAM: 8GB
disk: SSD
OS: Ubuntu 18.04

One MySQL vm + Three k3s master nodes

**Comment by brandond** [comment] 2020-07-29 22:57
@haydnhkim pod logs are not stored in the kubernetes datastore - they are retrieved from docker or containerd on demand. While the crashloops may have created many events that are stored in the kubernetes datastore, this still should not consume 20GB of database space. Are you seeing any errors in the k3s or database logs?

**Comment by haydnhkim** [comment] 2020-07-30 15:07
Oops, sorry. I have two cluters, CrashLoopBackOff was happening in only one cluster. However, regardless of CrashLoopBackOff, the capacity of mysql increased in both clusters.
As you say, the pod's log doesn't matter.

I thought there might be another reason, and I found it was a problem with `binlog` in the lib/mysql directory!
1.1 GB of binlogs were created every day. I will solve the problem by setting expire_logs_days.
Thank you!

**Comment by brandond** [comment] 2020-07-30 17:18
If anyone else runs into this issue, and can confirm that it is due excessive number of rows in the kine table (gap records, old rows not getting deleted), I would be interested in getting a copy of your database.

**Comment by nayrnet** [comment] 2020-10-29 16:33
the following script has been used successfully to manually compact k3s MySQL databases that have encountered this issue: https://gist.github.com/dkeightley/bf350461ea3911a085566b850097d04d

**Comment by brandond** [comment] 2020-10-29 17:53
This should be resolved with the updates referenced above. Compaction is now done in a single transaction to avoid conflicts, and uses an optimized SQL query that should allow it to remove old revisions much faster than previously.

Note that the script above does NOT use a transaction and should probably only be run offline to avoid conflicting with the built-in compaction.

**Comment by davidnuzik** [comment] 2020-10-29 18:47
Moving to Test.

**Comment by rancher-max** [comment] 2020-10-29 19:17
#### Validated using v1.17.13-rc1+k3s2 and v1.18.10-rc1+k3s2

- There are now useful logs that show the compaction happening very 5 minutes:
```
Oct 29 17:16:05 ip-172-31-0-86 k3s[4490]: time="2020-10-29T17:16:05.255560500Z" level=debug msg="COMPACT deleted 623 rows from 1000 revisions in 22.476092ms - compacted to 1002/3567"
Oct 29 17:16:05 ip-172-31-0-86 k3s[4490]: time="2020-10-29T17:16:05.290560618Z" level=debug msg="COMPACT deleted 737 rows from 737 revisions in 21.395466ms - compacted to 1739/3567"
```
- Previously, there were no logs, so made some comparisons directly on DB between older k3s versions and these newer versions. The workloads on the clusters were the same. Steps:
  - Create single node k3s cluster with mysql backend
  - Import the cluster into a rancher server
  - Consistently run the following queries every minute:
```
select * from kine where name like "%compact_rev_key%";
select count(*) from kine;
```
  - Noticed how overall count was always lower in the newer versions, despite actually having them running longer.
  - I did not notice any duplicate keys being created for any of the versions under test, but it seems in a setup that has seen the high disk usage, this would be fixed based on the other findings. Additionally, the prev_revision value was always moving up by greater than 1000.
- Overall compaction time taking a few milliseconds whereas previously based on Brad's assertions it took seconds. Snippet from logs of versions with the update above.

My test above does not fully validate the errors seen in this issue as my DB was not around very long and not growing indefinitely, so I want to leave this open for a bit as users use the new versions and hopefully see resolutions to their DBs and k3s clusters.

**Closed** 2020-10-29 19:22 UTC
Labels: [zube]: To Test, internal, kind/bug, priority/critical-urgent, status/blocker

**Comment by dfoxg** [comment] 2022-01-13 20:30
Can i safely delete the entrys with the name like gab-%? My fresh installed k3s cluster (1 day old) has generated 12305 gab-entrys.


Also after one week my complete cluster gets in a invalid state with a grown database - the mysql-dump from the latest crash shows 209156 gab entrys with a total count of 350000 entrys. Im running on the latest k3s version (v1.22.5+k3s1 (405bf79d)) with a mariadb galera cluster (mariadb  Ver 15.1 Distrib 10.6.5-MariaDB, for debian-linux-gnu (x86_64) using readline EditLine wrapper)

**Comment by brandond** [comment] 2022-01-13 22:33
No, don't manually delete the gap records.

Galaera probably isn't a great choice. Kine expects the auto-increment ID field to increase by one per insert, while most distributed multi-master database engines increase this by some other number - usually the number of masters in the cluster. See https://galeracluster.com/library/kb/auto-increment-multiples.html and https://github.com/k3s-io/kine/issues/71

**Comment by dfoxg** [comment] 2022-01-14 05:45
Thanks for the quick reply. I think a note in the documentation about this restriction is necessary.

**Comment by unixfox** [comment] 2022-01-14 09:14
> @dfoxg No, don't manually delete the gap records.
> 
> Galaera probably isn't a great choice. Kine expects the auto-increment ID column to increase by one per insert, while most distributed multi-master database engines increase this by some other number - usually the number of masters in the cluster - which leaves gaps in the sequence. See [galeracluster.com/library/kb/auto-increment-multiples.html](https://galeracluster.com/library/kb/auto-increment-multiples.html) and [k3s-io/kine#71](https://github.com/k3s-io/kine/issues/71)

What solution do you recommend for a cluster mysql or mariadb instead of using galera?

**Comment by dfoxg** [comment] 2022-01-14 09:16
I think the best way is the embedded etcd in k3s. I will switch to it

**Comment by brandond** [comment] 2022-01-14 09:33
We usually see it used with managed database services like RDS where HA is part of the service offering, or in smaller environments with an existing database infrastructure that's already HA.

**Comment by nxtcoder17** [comment] 2022-11-09 06:47
we also experienced this issue, going into PVC, we figured out, high disk usage was because of `mysql` dumping logs in the `/bitnami/mysql` mounted PVC as filenames `mysql-bin.*`

In our case, these files were 1.1GBs in size, removing it fixed high disk usage

**Comment by Brennwert** [comment] 2023-01-02 13:57
> @brandond Oops, sorry. I have two clusters, CrashLoopBackOff was happening in only one cluster. However, regardless of CrashLoopBackOff, the capacity of mysql increased in both clusters. As you say, the pod's log doesn't matter.
> 
> I thought there might be another reason, and I found it was a problem with `binlog` in the lib/mysql directory! 1.1 GB of binlogs were created every day. I solved the problem by setting expire_logs_days. I hope this comment will help someone with the same problem. Thank you!

This comment helped me, thanks a lot!
I ended up setting the binlog-retention to 5 days by using: 

`binlog_expire_logs_seconds=432000`

**Comment by brandond** [comment] 2023-01-02 18:56
> to clear previous revisions from kine

DO NOT run the given command while the database is in use. Kine manages compaction (removal of old revisions) on its own. Running this command may break watches or other clients that depend on a recent window of old revisions existing.

**Comment by mrmimo** [comment] 2024-08-20 14:54
I've found this issue as I had similar problem that I solved. I thought this case may be helpful for anyone.

I'm using gallera with k3s (Kubernetes Version: v1.26.15 +k3s1).  

In my case at some point in time my database started to grow. As I investigated it deeper I've found out that the compaction process was often stopped by deadlocks. My kine had 7M records, some keys had 200-300k versions. I've read that gallera is discouraged in this thread, but gallera is easy to setup and to manage on the other hand. So I decided to give it a chance.

I reconfigured haproxy in front of the gallera cluster to drive the traffic to a single server (i.e. single master mode), and it only uses other server as a backup. In 15 minutes my database was compacted to 10k of records. 

So if you want to go with gallera it seems to work, but only if you write to a single server. I have also browsed through the sources of kine. It is true that by using autoincrements of 2 there are gap-* records produced. In a single master mode you can practically change it to 1. Haven't tested it yet, though.
