### ISSUE TITLE
Install fail since last merge (install.sh) : Unit k3s.service is not loaded properly: Invalid argument.

### ISSUE THREAD

**Issue by rebrec** [rancher/k3s#966] opened 2019-10-26 22:41 UTC
My problem is not related to a k3s version.

It seems that since the last merge https://github.com/rancher/k3s/pull/965

I am getting an error at the end of the installation of k3s using the install.sh

# Example installation with latest version of install.sh :

```
# curl -sfL https://raw.githubusercontent.com/rancher/k3s/master/install.sh | sh -
[INFO]  Finding latest release
[INFO]  Using v0.10.0 as release
[INFO]  Downloading hash https://github.com/rancher/k3s/releases/download/v0.10.0/sha256sum-amd64.txt
[INFO]  Downloading binary https://github.com/rancher/k3s/releases/download/v0.10.0/k3s
[INFO]  Verifying binary download
[INFO]  Installing k3s to /usr/local/bin/k3s
[INFO]  Creating /usr/local/bin/kubectl symlink to k3s
[INFO]  Creating /usr/local/bin/crictl symlink to k3s
[INFO]  Creating /usr/local/bin/ctr symlink to k3s
[INFO]  Creating killall script /usr/local/bin/k3s-killall.sh
[INFO]  Creating uninstall script /usr/local/bin/k3s-uninstall.sh
[INFO]  env: Creating environment file /etc/systemd/system/k3s.service.env
[INFO]  systemd: Creating service file /etc/systemd/system/k3s.service
[INFO]  systemd: Enabling k3s unit
Created symlink /etc/systemd/system/multi-user.target.wants/k3s.service → /etc/systemd/system/k3s.service.
[INFO]  systemd: Starting k3s
**Failed to restart k3s.service: Unit k3s.service is not loaded properly: Invalid argument.**
See system logs and 'systemctl status k3s.service' for details.
```

# Now the same command with a previous commit :

```
root@ubuntu-s-2vcpu-4gb-ams3-01:~# curl -sfL https://raw.githubusercontent.com/rancher/k3s/e3cd52a49e901074a77ba7da6e4ee2ea3e10e669/install.sh | sh -
[INFO]  Finding latest release
[INFO]  Using v0.10.0 as release
[INFO]  Downloading hash https://github.com/rancher/k3s/releases/download/v0.10.0/sha256sum-amd64.txt
[INFO]  Skipping binary downloaded, installed k3s matches hash
[INFO]  Skipping /usr/local/bin/kubectl symlink to k3s, already exists
[INFO]  Skipping /usr/local/bin/crictl symlink to k3s, already exists
[INFO]  Skipping /usr/local/bin/ctr symlink to k3s, already exists
[INFO]  Creating killall script /usr/local/bin/k3s-killall.sh
[INFO]  Creating uninstall script /usr/local/bin/k3s-uninstall.sh
[INFO]  env: Creating environment file /etc/systemd/system/k3s.service.env
[INFO]  systemd: Creating service file /etc/systemd/system/k3s.service
[INFO]  systemd: Enabling k3s unit
Created symlink /etc/systemd/system/multi-user.target.wants/k3s.service → /etc/systemd/system/k3s.service.
[INFO]  systemd: Starting k3s
```

Hope it help.

Thanks for your nice work btw

**Comment by erikwilson** [comment] 2019-10-26 22:56
Thanks for the info @rebrec, can you also share the os version and systemd version?

**Comment by erikwilson** [comment] 2019-10-27 00:14
I was able to reproduce with Ubuntu 16.04, systemd --version 229.
Fixed by adding a trailing newline to the service file.
Change was because newer systemd versions were appending `KillMode=process` rather than using it as a configuration value. :(
Guess systemd has lots of line continuation issues (╯°□°)╯︵ pɯǝʇsʎs

Many thanks for reporting again @rebrec, closing as fixed but please reopen if you continue to have issues!

**Closed by erikwilson** 2019-10-27 00:14 UTC

**Comment by rebrec** [comment] 2019-10-27 17:38
@erikwilson sorry for the late reply : 

OS Version : Ubuntu 18.04.3 LTS
Systemd version : 237

Thanks for fixing it
