### ISSUE TITLE
Cannot remount block device PersistentVolumes on k3s v1.18

### ISSUE THREAD

**Issue by brandond** [rancher/k3s#1682] opened 2020-04-25 09:11 UTC
**Version:**
k3s version v1.18.2-rc2+k3s1 (2c493411)

**K3s arguments:**
```
ExecStart=/usr/local/bin/k3s \
    server \
        '--disable=coredns,servicelb,traefik,local-storage,metrics-server' \
        '--disable-cloud-controller' \
        '--disable-network-policy' \
        '--flannel-backend=host-gw' \
        '--write-kubeconfig-mode=664' \
        '--datastore-endpoint=http://localhost:2379' \
```

**Describe the bug**
XFS volumes fail to mount with mkfs.xfs error. Ext3/4 filesystems may be wiped due to the force flag? I haven't tested it.
```
 Warning  FailedMount             14s (x6 over 30s)  kubelet, sealand.khaus   MountVolume.MountDevice failed for volume "pvc-4b9ea207-80aa-4ef6-88d0-d8bf4f57f064" : format of disk "/dev/disk/by-path/ip-10.43.101.30:3260-iscsi-iqn.2016-09.com.openebs.cstor:pvc-4b9ea207-80aa-4ef6-88d0-d8bf4f57f064-lun-0" failed: type:("xfs") target:("/var/lib/kubelet/plugins/kubernetes.io/iscsi/iface-default/10.43.101.30:3260-iqn.2016-09.com.openebs.cstor:pvc-4b9ea207-80aa-4ef6-88d0-d8bf4f57f064-lun-0") options:("defaults") errcode:(exit status 1) output:(mkfs.xfs: /dev/disk/by-path/ip-10.43.101.30:3260-iscsi-iqn.2016-09.com.openebs.cstor:pvc-4b9ea207-80aa-4ef6-88d0-d8bf4f57f064-lun-0 appears to contain an existing filesystem (xfs).
mkfs.xfs: Use the -f option to force overwrite.
```

PVs can be mounted successfully only once. Subsequent use by pods will fail. If a broken pod and pvc are deleted, after waiting for the pv to delete, you can then recreate the pod and pvc, and the new pv is correctly formatted and mounted.

**To Reproduce**
* Install k3s v1.18+
* Install a block CSI such as Longhorn or OpenEBS
* Create a StorageClass using the block CSI
* Create a Deployment with a PersistentVolumeClaim backed by the block StorageClass
* Delete the pod
* Check the status on the new pod. It should be stuck waiting for the volume to mount.

**Expected behavior**
Volume should mount

**Actual behavior**
Volume fails to mount

**Additional context / logs**
logs from `k3s server --vmodule=mount_linux=4`

```
Apr 27 16:10:43 seago k3s[2569964]: E0427 16:10:43.624613 2569964 kubelet.go:1681] Unable to attach or mount volumes for pod "prometheus-8c97866fc-m9dlb_monitoring-system(d145263b-0f65-4011-83a3-d2de3a991f21)": unmounted volumes=[prometheus-data], unattached volumes=[prometheus-data prometheus-token-nx4gs config-volume]: timed out waiting for the condition; skipping pod
Apr 27 16:10:43 seago k3s[2569964]: E0427 16:10:43.624698 2569964 pod_workers.go:191] Error syncing pod d145263b-0f65-4011-83a3-d2de3a991f21 ("prometheus-8c97866fc-m9dlb_monitoring-system(d145263b-0f65-4011-83a3-d2de3a991f21)"), skipping: unmounted volumes=[prometheus-data], unattached volumes=[prometheus-data prometheus-token-nx4gs config-volume]: timed out waiting for the condition
Apr 27 16:12:42 seago k3s[2569964]: I0427 16:12:42.790725 2569964 operation_generator.go:558] MountVolume.WaitForAttach entering for volume "pvc-9551f4d8-810a-42a7-b416-6e4d66b32b12" (UniqueName: "kubernetes.io/iscsi/10.43.5.61:3260:iqn.2016-09.com.openebs.cstor:pvc-9551f4d8-810a-42a7-b416-6e4d66b32b12:0") pod "prometheus-8c97866fc-m9dlb" (UID: "d145263b-0f65-4011-83a3-d2de3a991f21") DevicePath ""
Apr 27 16:12:42 seago k3s[2569964]: I0427 16:12:42.794282 2569964 mount_linux.go:405] Attempting to determine if disk "/dev/disk/by-path/ip-10.43.5.61:3260-iscsi-iqn.2016-09.com.openebs.cstor:pvc-9551f4d8-810a-42a7-b416-6e4d66b32b12-lun-0" is formatted using blkid with args: ([-p -s TYPE -s PTTYPE -o export /dev/disk/by-path/ip-10.43.5.61:3260-iscsi-iqn.2016-09.com.openebs.cstor:pvc-9551f4d8-810a-42a7-b416-6e4d66b32b12-lun-0])
Apr 27 16:12:42 seago k3s[2569964]: I0427 16:12:42.799275 2569964 mount_linux.go:408] Output: "", err: <nil>
Apr 27 16:12:42 seago k3s[2569964]: I0427 16:12:42.799309 2569964 mount_linux.go:366] Disk "/dev/disk/by-path/ip-10.43.5.61:3260-iscsi-iqn.2016-09.com.openebs.cstor:pvc-9551f4d8-810a-42a7-b416-6e4d66b32b12-lun-0" appears to be unformatted, attempting to format as type: "xfs" with options: [/dev/disk/by-path/ip-10.43.5.61:3260-iscsi-iqn.2016-09.com.openebs.cstor:pvc-9551f4d8-810a-42a7-b416-6e4d66b32b12-lun-0]
Apr 27 16:12:42 seago k3s[2569964]: E0427 16:12:42.822026 2569964 mount_linux.go:372] format of disk "/dev/disk/by-path/ip-10.43.5.61:3260-iscsi-iqn.2016-09.com.openebs.cstor:pvc-9551f4d8-810a-42a7-b416-6e4d66b32b12-lun-0" failed: type:("xfs") target:("/var/lib/kubelet/plugins/kubernetes.io/iscsi/iface-default/10.43.5.61:3260-iqn.2016-09.com.openebs.cstor:pvc-9551f4d8-810a-42a7-b416-6e4d66b32b12-lun-0") options:("defaults") errcode:(exit status 1) output:(mkfs.xfs: /dev/disk/by-path/ip-10.43.5.61:3260-iscsi-iqn.2016-09.com.openebs.cstor:pvc-9551f4d8-810a-42a7-b416-6e4d66b32b12-lun-0 appears to contain an existing filesystem (xfs).
Apr 27 16:12:42 seago k3s[2569964]: mkfs.xfs: Use the -f option to force overwrite.
Apr 27 16:12:42 seago k3s[2569964]: )
Apr 27 16:12:42 seago k3s[2569964]: E0427 16:12:42.822059 2569964 iscsi_util.go:510] iscsi: failed to mount iscsi volume /dev/disk/by-path/ip-10.43.5.61:3260-iscsi-iqn.2016-09.com.openebs.cstor:pvc-9551f4d8-810a-42a7-b416-6e4d66b32b12-lun-0 [xfs] to /var/lib/kubelet/plugins/kubernetes.io/iscsi/iface-default/10.43.5.61:3260-iqn.2016-09.com.openebs.cstor:pvc-9551f4d8-810a-42a7-b416-6e4d66b32b12-lun-0, error format of disk "/dev/disk/by-path/ip-10.43.5.61:3260-iscsi-iqn.2016-09.com.openebs.cstor:pvc-9551f4d8-810a-42a7-b416-6e4d66b32b12-lun-0" failed: type:("xfs") target:("/var/lib/kubelet/plugins/kubernetes.io/iscsi/iface-default/10.43.5.61:3260-iqn.2016-09.com.openebs.cstor:pvc-9551f4d8-810a-42a7-b416-6e4d66b32b12-lun-0") options:("defaults") errcode:(exit status 1) output:(mkfs.xfs: /dev/disk/by-path/ip-10.43.5.61:3260-iscsi-iqn.2016-09.com.openebs.cstor:pvc-9551f4d8-810a-42a7-b416-6e4d66b32b12-lun-0 appears to contain an existing filesystem (xfs).
Apr 27 16:12:42 seago k3s[2569964]: mkfs.xfs: Use the -f option to force overwrite.
Apr 27 16:12:42 seago k3s[2569964]: )
Apr 27 16:12:42 seago k3s[2569964]: I0427 16:12:42.822102 2569964 operation_generator.go:567] MountVolume.WaitForAttach succeeded for volume "pvc-9551f4d8-810a-42a7-b416-6e4d66b32b12" (UniqueName: "kubernetes.io/iscsi/10.43.5.61:3260:iqn.2016-09.com.openebs.cstor:pvc-9551f4d8-810a-42a7-b416-6e4d66b32b12:0") pod "prometheus-8c97866fc-m9dlb" (UID: "d145263b-0f65-4011-83a3-d2de3a991f21") DevicePath "/dev/disk/by-path/ip-10.43.5.61:3260-iscsi-iqn.2016-09.com.openebs.cstor:pvc-9551f4d8-810a-42a7-b416-6e4d66b32b12-lun-0"
Apr 27 16:12:42 seago k3s[2569964]: I0427 16:12:42.822151 2569964 mount_linux.go:405] Attempting to determine if disk "/dev/disk/by-path/ip-10.43.5.61:3260-iscsi-iqn.2016-09.com.openebs.cstor:pvc-9551f4d8-810a-42a7-b416-6e4d66b32b12-lun-0" is formatted using blkid with args: ([-p -s TYPE -s PTTYPE -o export /dev/disk/by-path/ip-10.43.5.61:3260-iscsi-iqn.2016-09.com.openebs.cstor:pvc-9551f4d8-810a-42a7-b416-6e4d66b32b12-lun-0])
Apr 27 16:12:42 seago k3s[2569964]: I0427 16:12:42.829571 2569964 mount_linux.go:408] Output: "", err: <nil>
Apr 27 16:12:42 seago k3s[2569964]: I0427 16:12:42.829609 2569964 mount_linux.go:366] Disk "/dev/disk/by-path/ip-10.43.5.61:3260-iscsi-iqn.2016-09.com.openebs.cstor:pvc-9551f4d8-810a-42a7-b416-6e4d66b32b12-lun-0" appears to be unformatted, attempting to format as type: "xfs" with options: [/dev/disk/by-path/ip-10.43.5.61:3260-iscsi-iqn.2016-09.com.openebs.cstor:pvc-9551f4d8-810a-42a7-b416-6e4d66b32b12-lun-0]
Apr 27 16:12:42 seago k3s[2569964]: E0427 16:12:42.844296 2569964 mount_linux.go:372] format of disk "/dev/disk/by-path/ip-10.43.5.61:3260-iscsi-iqn.2016-09.com.openebs.cstor:pvc-9551f4d8-810a-42a7-b416-6e4d66b32b12-lun-0" failed: type:("xfs") target:("/var/lib/kubelet/plugins/kubernetes.io/iscsi/iface-default/10.43.5.61:3260-iqn.2016-09.com.openebs.cstor:pvc-9551f4d8-810a-42a7-b416-6e4d66b32b12-lun-0") options:("defaults") errcode:(exit status 1) output:(mkfs.xfs: /dev/disk/by-path/ip-10.43.5.61:3260-iscsi-iqn.2016-09.com.openebs.cstor:pvc-9551f4d8-810a-42a7-b416-6e4d66b32b12-lun-0 appears to contain an existing filesystem (xfs).
Apr 27 16:12:42 seago k3s[2569964]: mkfs.xfs: Use the -f option to force overwrite.
Apr 27 16:12:42 seago k3s[2569964]: )
Apr 27 16:12:42 seago k3s[2569964]: E0427 16:12:42.844421 2569964 nestedpendingoperations.go:301] Operation for "{volumeName:kubernetes.io/iscsi/10.43.5.61:3260:iqn.2016-09.com.openebs.cstor:pvc-9551f4d8-810a-42a7-b416-6e4d66b32b12:0 podName: nodeName:}" failed. No retries permitted until 2020-04-27 16:14:44.84438001 -0700 PDT m=+18457.955783250 (durationBeforeRetry 2m2s). Error: "MountVolume.MountDevice failed for volume \"pvc-9551f4d8-810a-42a7-b416-6e4d66b32b12\" (UniqueName: \"kubernetes.io/iscsi/10.43.5.61:3260:iqn.2016-09.com.openebs.cstor:pvc-9551f4d8-810a-42a7-b416-6e4d66b32b12:0\") pod \"prometheus-8c97866fc-m9dlb\" (UID: \"d145263b-0f65-4011-83a3-d2de3a991f21\") : format of disk \"/dev/disk/by-path/ip-10.43.5.61:3260-iscsi-iqn.2016-09.com.openebs.cstor:pvc-9551f4d8-810a-42a7-b416-6e4d66b32b12-lun-0\" failed: type:(\"xfs\") target:(\"/var/lib/kubelet/plugins/kubernetes.io/iscsi/iface-default/10.43.5.61:3260-iqn.2016-09.com.openebs.cstor:pvc-9551f4d8-810a-42a7-b416-6e4d66b32b12-lun-0\") options:(\"defaults\") errcode:(exit status 1) output:(mkfs.xfs: /dev/disk/by-path/ip-10.43.5.61:3260-iscsi-iqn.2016-09.com.openebs.cstor:pvc-9551f4d8-810a-42a7-b416-6e4d66b32b12-lun-0 appears to contain an existing filesystem (xfs).\nmkfs.xfs: Use the -f option to force overwrite.\n) "
```

**Comment by brandond** [comment] 2020-04-27 18:25
@ibuildthecloud this appears to be an issue with the `blkid` provided by the bundled busybox.

The system blkid detects the volume fs properly:
```
root@seago:/var/lib/rancher/k3s/data/1cd84d78e73d1835ec46d86660cd74dd4d52357ced9b4050a211168c4b1da90a/bin# blkid /dev/disk/by-path/ip-10.43.5.61:3260-iscsi-iqn.2016-09.com.openebs.cstor:pvc-9551f4d8-810a-42a7-b416-6e4d66b32b12-lun-0; echo retval=$?
/dev/disk/by-path/ip-10.43.5.61:3260-iscsi-iqn.2016-09.com.openebs.cstor:pvc-9551f4d8-810a-42a7-b416-6e4d66b32b12-lun-0: UUID="11a2af42-00c9-4660-917f-191d45679885" TYPE="xfs"
retval=0
```

The busybox blkid does not:
```
root@seago:/var/lib/rancher/k3s/data/1cd84d78e73d1835ec46d86660cd74dd4d52357ced9b4050a211168c4b1da90a/bin# ./busybox blkid /dev/disk/by-path/ip-10.43.5.61:3260-iscsi-iqn.2016-09.com.openebs.cstor:pvc-9551f4d8-810a-42a7-b416-6e4d66b32b12-lun-0; echo retval=$?
retval=0
```

**Comment by brandond** [comment] 2020-04-27 22:02
A fresh download of busybox from https://busybox.net/downloads/binaries/1.31.0-i686-uclibc/busybox works fine.

I think the underlying issue here is that k8s previously blindly attempted to mount the volume, and then would check the filesystem if the mount failed. 

https://github.com/kubernetes/kubernetes/blob/release-1.17/vendor/k8s.io/utils/mount/mount_linux.go#L298
https://github.com/kubernetes/kubernetes/blob/release-1.18/vendor/k8s.io/utils/mount/mount_linux.go#L340

k8s now calls `mounter.GetDiskFormat` before attempting to mount. Since that in turn calls `blkid`, and k3s is bundling busybox's blkid without xfs support, xfs volumes will fail to remount every time - only the initial mount can ever succeed.

**Comment by brandond** [comment] 2020-04-27 22:08
Here's the root cause:
https://github.com/rancher/k3s-root/blob/master/busybox.config#L720

**Comment by erikwilson** [comment] 2020-04-29 18:10
Is it possibly related to this: https://github.com/rancher/k3s/issues/495#issuecomment-521645775 ?

Looks like a different error, but need to use xfs_info to verify that the ftype option is set to 1.

**Comment by brandond** [comment] 2020-04-29 18:21
@erikwilson my initial problem was XFS specific, but it turns out the k3s-root busybox `blkid` was compiled without the flag to output the TYPE field, in addition to lacking xfs support. Even with those two issues fixed, it still doesn't output the fields in the correct format.

k8s 1.18 changed the mount code path such that blkid gets called before attempting to mount the block device, whereas earlier release only called blkid if the mount failed. Since the k3s bundled blkid is completely unusable for ANY filesystem in its current state, block storage is completely broken until https://github.com/rancher/k3s-root/pull/8 is merged. The first mount (that formats the volume) will succeed, but subsequent mounts will fail.

**Comment by erikwilson** [comment] 2020-04-29 18:44
Thanks @brandond for digging into this and finding a solution!

It is probably best to update blkid in k3s-root, another option might be to prefer the host blkid executable as we do with mount: https://github.com/rancher/k3s/blob/690a4ca7a4eb55d373f9390475842943e067df30/scripts/download#L18

Will have an internal discussion and work on getting a fix through, many thanks again!

**Comment by brandond** [comment] 2020-04-29 18:58
@erikwilson the first option what that PR does, just configures buildroot to use the util-linux blkid instead of busybox.

Is the point of k3s-root to ensure the existence of various utilities that might not be available or functional on the host? In that case, keeping a functional blkid in there is probably the better option, for distros like alpine that might be using busybox's broken blkid.

**Comment by erikwilson** [comment] 2020-04-29 19:30
I see, yes, thank you, we should provide a standard set of tools which just work, which means updating k3s-root and defaulting to that util-linux version of blkid. 

It would be ideal if alpine/busybox/kubernetes could play nicely together tho.

**Comment by erikwilson** [comment] 2020-04-30 19:13
@brandond thanks again for reporting this, would you be able to provide some more information such as which OS you are using and an example yaml for testing?

While testing with longhorn on CentOS7 I was trying:
```sh
kubectl apply -f https://raw.githubusercontent.com/longhorn/longhorn/master/deploy/longhorn.yaml
kubectl apply -f https://raw.githubusercontent.com/longhorn/longhorn/ebeaff7d6719de6fe85b74ccf09f88569f43c4e5/examples/block_volume.yaml 
```

then will get a `losetup` error like:
```
  Warning  FailedMapVolume         4m (x11 over 10m)      kubelet, k3s-3-centos7   MapVolume.MapBlockVolume failed for volume "pvc-813a5216-815d-415e-91c3-25d6634a1cee" : blkUtil.AttachFileDevice failed. globalMapPath:/var/lib/kubelet/plugins/kubernetes.io/csi/volumeDevices/pvc-813a5216-815d-415e-91c3-25d6634a1cee/dev, podUID: da564756-6fef-45cc-a12e-c99340047d80: GetLoopDevice failed for path /var/lib/kubelet/plugins/kubernetes.io/csi/volumeDevices/pvc-813a5216-815d-415e-91c3-25d6634a1cee/dev/da564756-6fef-45cc-a12e-c99340047d80: losetup -j /var/lib/kubelet/plugins/kubernetes.io/csi/volumeDevices/pvc-813a5216-815d-415e-91c3-25d6634a1cee/dev/da564756-6fef-45cc-a12e-c99340047d80 failed: exit status 1
```

We can get past the losetup error by removing it to prefer the system version (seems that it should be fixed in k3s-root too) via`rm /var/lib/rancher/k3s/data/*/bin/losetup`, but then removing and recreating the pod works and doesn't trigger the blkid problem.

**Comment by brandond** [comment] 2020-04-30 21:48
I'm using OpenEBS on a 3-node Ubuntu 20.04 homelab setup. I'll see if I can set up an easy replication with single-node Longhorn.

You might try using xfs instead of letting k8s default the filesystem to ext4. One of the surprising things I found was that it will force-format the volume if you're using ext3 or ext4:
https://github.com/kubernetes/kubernetes/blob/master/vendor/k8s.io/utils/mount/mount_linux.go#L360
This could be allowing the volume to mount properly, while silently wiping it.

xfs doesn't get any special flags appended to the mkfs command, which was why I was getting a mkfs.xfs error when blkid failed to identify the existing filesystem.

**Comment by yasker** [comment] 2020-04-30 23:27
Thanks for the report @brandond . We've tried to reproduce the issue on Longhorn too but then realized the current Longhorn codebase wasn't compiled against the Kubernetes 1.18 (since the function `formatAndMountSensitive` is used as a library rather than RPC call) , so Longhorn isn't affected by this bug at the moment. But it will be an issue when we release a new version based on Kubernetes 1.18.

**Comment by cjellick** [comment] 2020-05-01 16:24
@brandond thanks again for identifying and fixing this issue. We are actually holding up the 1.18.2 release to address it. Took us awhile to understand it, largely because we were testing with longhorn at first which is currently unaffected (but will be eventually).

If you have time today, over the weekend, or next week, could you ping me on Rancher's user slack? I want to ask a follow up question.

**Comment by brandond** [comment] 2020-05-01 21:29
Nice of github to automatically close this issue every time someone pulls that commit. My fault for tagging it as fixes in the message I guess.

**Comment by cjellick** [comment] 2020-05-05 01:47
@brandond we have an rc with your fix (and a few other tweaks). Can you test it out?

**Comment by ShylajaDevadiga** [comment] 2020-05-05 02:30
Verified on k3s v1.18.2-rc3+k3s1
```
k3s -v
k3s version v1.18.2-rc3+k3s1 (a013f7dd)
root@ip-172-31-2-90:~# blkid /dev/sda
/dev/sda: UUID="a879a9da-3d4f-42e8-adbb-710fc519a610" TYPE="xfs"
root@ip-172-31-2-90:~# /var/lib/rancher/k3s/data/85ad3428a47fc614c88dbb09a644abbc71f18d9ecb55aaa5040866c83f273dd4/bin/blkid /dev/sda 
/dev/sda: UUID="a879a9da-3d4f-42e8-adbb-710fc519a610" TYPE="xfs"
root@ip-172-31-2-90:~# 
```

**Comment by brandond** [comment] 2020-05-05 08:46
I commented over at https://github.com/rancher/k3s/pull/1737#issuecomment-623727581 but yeah, can confirm issue is resolved. Thanks!

**Comment by davidnuzik** [comment] 2020-05-05 16:48
Closing as fix has been verified per comments.

**Closed by davidnuzik** 2020-05-05 16:48 UTC
Labels: kind/bug
